/**
 * BookshelfPeek — autonomous peek overlay for BOOKSHELF tiles.
 *
 * 3-phase animation (matches DoorPeek pattern):
 *   Phase 1 (closed):  Player faces a BOOKSHELF/TERMINAL tile. 3D bookshelf appears.
 *   Phase 2 (cracked): Auto-advances on adjacency (~200ms). 📚 emoji animates, title appears.
 *   Phase 3 (opened):  Forward input or action button click. 📚 fully visible. DialogBox opens.
 *                      3D box stays visible behind dialog.
 *
 * Content delivery via DialogBox remains unchanged. Supports multi-page navigation,
 * terminal/CRT styling, and player flag tracking for read books.
 *
 * CSS 3D animation from BOOKSHELF_ANIMATION.md (BoxForge v1.0 variant).
 * Self-contained — no BoxAnim dependency.
 *
 * Layer 2 (Level 3 in load order due to dependencies) — depends on:
 *   TILES, Player, MovementController, FloorManager, DialogBox, AudioSystem,
 *   InputManager (for forward/back edge detection)
 */
var BookshelfPeek = (function () {
  'use strict';

  var MC = typeof MovementController !== 'undefined' ? MovementController : null;

  // ── Config ──────────────────────────────────────────────────────
  var SHOW_DELAY = 400;  // ms debounce before peek shows
  var HIDE_DELAY = 200;  // ms before peek hides after looking away

  // ── Book catalog (loaded from data/books.json) ──────────────────
  var _catalog = [];           // Array of book objects
  var _catalogById = {};       // id → book lookup
  var _catalogByBiome = {};    // biome → [book, book, ...]
  var _catalogByCategory = {}; // category → [book, book, ...]
  var _loaded = false;

  // ── State ───────────────────────────────────────────────────────
  var _active      = false;
  var _phase       = 0;       // 0=inactive, 1=closed, 2=hovered, 3=opened
  var _timer       = 0;
  var _hideTimer   = 0;
  var _facingX     = -1;
  var _facingY     = -1;
  var _currentBook = null;    // Currently displayed book object
  var _currentPage = 0;       // Current page index

  // ── 3D box state ────────────────────────────────────────────────
  var _container3d  = null;
  var _wrap         = null;
  var _labelLayer   = null;
  var _subLabel     = null;
  var _actionBtn    = null;
  var _styleInjected = false;

  // Forward/back edge tracking (BookshelfPeek runs after InputPoll)
  var _prevForward = false;
  var _prevBack    = false;

  // ── Load catalog ────────────────────────────────────────────────

  function _loadCatalog() {
    if (_loaded) return;
    try {
      var xhr = new XMLHttpRequest();
      xhr.open('GET', 'data/books.json', false); // Sync load at init
      xhr.send();
      if (xhr.status === 200 || xhr.status === 0) {
        var data = JSON.parse(xhr.responseText);
        _catalog = data.books || [];
        for (var i = 0; i < _catalog.length; i++) {
          var book = _catalog[i];
          _catalogById[book.id] = book;
          if (!_catalogByBiome[book.biome]) _catalogByBiome[book.biome] = [];
          _catalogByBiome[book.biome].push(book);
          if (book.category) {
            if (!_catalogByCategory[book.category]) _catalogByCategory[book.category] = [];
            _catalogByCategory[book.category].push(book);
          }
        }
        _loaded = true;
        console.log('[BookshelfPeek] Loaded ' + _catalog.length + ' books');
      } else {
        // Non-200/non-0 status (e.g. 404, 403) — mark loaded to prevent
        // infinite retries, but log the failure for debugging.
        console.warn('[BookshelfPeek] books.json returned status ' + xhr.status + '; shelves will use biome fallback');
        _loaded = true;
      }
    } catch (e) {
      console.warn('[BookshelfPeek] Failed to load books.json:', e);
      _loaded = true; // Prevent retry loops
    }
  }

  // ── CSS injection ────────────────────────────────────────────────

  function _injectCSS() {
    if (_styleInjected) return;
    _styleInjected = true;

    // Base CSS from BOOKSHELF_ANIMATION.md
    var baseCss =
      '/* === Variant: bookshelf (299x303, depth 200) === */\n' +
      '/* Generated by BoxForge v1.0 — 6 panes (5 struct, 0 lid, 1 extra) */\n' +
      '\n' +
      '.box3d-wrap.bookshelf-variant {\n' +
      '  --bookshelf-w: 299px;\n' +
      '  --bookshelf-h: 303px;\n' +
      '  --box-d: 100px;\n' +
      '  --box-half: -100px;\n' +
      '  --bevel-w: 2px;\n' +
      '  --box-dark: #ffaf0f;\n' +
      '  --box-dark2: #e19100;\n' +
      '  --box-light: #472b00;\n' +
      '  --box-floor: #221d16;\n' +
      '  --box-ceil: #5a4020;\n' +
      '  --box-glow: rgba(26,0,224,0.6);\n' +
      '  --perspective: 427px;\n' +
      '  perspective: 427px;\n' +
      '  width: 299px;\n' +
      '  height: 303px;\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .box3d-scene {\n' +
      '  width: 299px; height: 303px;\n' +
      '  transform: rotateX(-28deg) rotateY(3deg);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .box3d-spin {\n' +
      '  width: 299px; height: 303px;\n' +
      '}\n' +
      '.bookshelf-variant .box3d-body {\n' +
      '  width: 299px; height: 303px;\n' +
      '}\n' +
      '\n' +
      '/* Back (back): 299 x 303 */\n' +
      '.box3d-wrap.bookshelf-variant .bf-back {\n' +
      '  width: 299px; height: 303px;\n' +
      '  background: linear-gradient(to top, #ffaf0f, #472b00);\n' +
      '  transform: translateZ(-100px) translate(0px,0px);\n' +
      '}\n' +
      '/* Left (left): 200 x 303 */\n' +
      '.box3d-wrap.bookshelf-variant .bf-left {\n' +
      '  width: 200px; height: 303px;\n' +
      '  left: 49.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #ffaf0f, #472b00);\n' +
      '  transform: translate(-149px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '/* Sub-box: depth 6px */\n' +
      '.box3d-wrap.bookshelf-variant .bf-left { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.bookshelf-variant .bf-left > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 200px; height: 303px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-6px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-left > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 303px;\n' +
      '  left: 94px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-100px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-left > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 303px;\n' +
      '  left: 94px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(100px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-left > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 200px; height: 12px;\n' +
      '  left: 0px; top: 145.5px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(151.5px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-left > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 200px; height: 12px;\n' +
      '  left: 0px; top: 145.5px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-151.5px) translateY(0px);\n' +
      '}\n' +
      '/* Right (right): 200 x 303 */\n' +
      '.box3d-wrap.bookshelf-variant .bf-right {\n' +
      '  width: 200px; height: 303px;\n' +
      '  left: 49.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #ffaf0f, #472b00);\n' +
      '  transform: translate(149px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '/* Sub-box: depth 6px */\n' +
      '.box3d-wrap.bookshelf-variant .bf-right { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.bookshelf-variant .bf-right > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 200px; height: 303px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-6px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-right > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 303px;\n' +
      '  left: 94px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-100px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-right > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 303px;\n' +
      '  left: 94px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(100px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-right > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 200px; height: 12px;\n' +
      '  left: 0px; top: 145.5px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(151.5px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-right > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 200px; height: 12px;\n' +
      '  left: 0px; top: 145.5px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-151.5px) translateY(0px);\n' +
      '}\n' +
      '/* Top (top): 299 x 200 */\n' +
      '.box3d-wrap.bookshelf-variant .bf-top {\n' +
      '  width: 299px; height: 200px;\n' +
      '  left: 0px; top: 51.5px;\n' +
      '  background: linear-gradient(to top, #ffaf0f, #472b00);\n' +
      '  transform: translate(1px,174.5px) rotateX(90deg) translateZ(151.5px) translateY(-27px);\n' +
      '}\n' +
      '/* Sub-box: depth 3px */\n' +
      '.box3d-wrap.bookshelf-variant .bf-top { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.bookshelf-variant .bf-top > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 299px; height: 200px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-3px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 6px; height: 200px;\n' +
      '  left: 146.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-149.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 6px; height: 200px;\n' +
      '  left: 146.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(149.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 299px; height: 6px;\n' +
      '  left: 0px; top: 97px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(100px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 299px; height: 6px;\n' +
      '  left: 0px; top: 97px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-100px) translateY(0px);\n' +
      '}\n' +
      '/* Bottom (bottom): 299 x 200 */\n' +
      '.box3d-wrap.bookshelf-variant .bf-bottom {\n' +
      '  width: 299px; height: 200px;\n' +
      '  left: 0px; top: 51.5px;\n' +
      '  background: linear-gradient(to top, #ffaf0f, #472b00);\n' +
      '  transform: translate(0px,-51.5px) rotateX(90deg) translateZ(-151.5px) translateY(0px);\n' +
      '}\n' +
      '/* Sub-box: depth 8px */\n' +
      '.box3d-wrap.bookshelf-variant .bf-bottom { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.bookshelf-variant .bf-bottom > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 299px; height: 200px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-8px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-bottom > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 16px; height: 200px;\n' +
      '  left: 141.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-149.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-bottom > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 16px; height: 200px;\n' +
      '  left: 141.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(149.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-bottom > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 299px; height: 16px;\n' +
      '  left: 0px; top: 92px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(100px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-bottom > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 299px; height: 16px;\n' +
      '  left: 0px; top: 92px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-100px) translateY(0px);\n' +
      '}\n' +
      '\n' +
      '/* === EXTRA PANES (1) === */\n' +
      '/* Lid (top, 289x256, role: structure) */\n' +
      '.box3d-wrap.bookshelf-variant .bf-top-2 {\n' +
      '  width: 289px; height: 256px;\n' +
      '  left: 5px; top: 23.5px;\n' +
      '  transform: translate(1px,43.5px) rotateX(90deg) translateZ(151.5px) translateY(-22px);\n' +
      '  background: linear-gradient(to top, #ffaf0f, #472b00);\n' +
      '}\n' +
      '/* Sub-box: depth 2px */\n' +
      '.box3d-wrap.bookshelf-variant .bf-top-2 { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.bookshelf-variant .bf-top-2 > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 289px; height: 256px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-2px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top-2 > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 4px; height: 256px;\n' +
      '  left: 142.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-144.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top-2 > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 4px; height: 256px;\n' +
      '  left: 142.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(144.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top-2 > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 289px; height: 4px;\n' +
      '  left: 0px; top: 126px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(128px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant .bf-top-2 > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 289px; height: 4px;\n' +
      '  left: 0px; top: 126px;\n' +
      '  background: linear-gradient(to top, #290d00, #472b00);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-128px) translateY(0px);\n' +
      '}\n' +
      '\n' +
      '/* === GLOW SOURCES (5) === */\n' +
      '.bookshelf-glow-0, .bookshelf-glow-1, .bookshelf-glow-2, .bookshelf-glow-3, .bookshelf-glow-4 {\n' +
      '  opacity: 0; transition: opacity 0.4s ease 0.15s; pointer-events: none;\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant.hovered .bookshelf-glow-0,\n' +
      '.box3d-wrap.bookshelf-variant.hovered .bookshelf-glow-1,\n' +
      '.box3d-wrap.bookshelf-variant.hovered .bookshelf-glow-2,\n' +
      '.box3d-wrap.bookshelf-variant.hovered .bookshelf-glow-3,\n' +
      '.box3d-wrap.bookshelf-variant.hovered .bookshelf-glow-4 {\n' +
      '  opacity: 0.5;\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant.opened .bookshelf-glow-0,\n' +
      '.box3d-wrap.bookshelf-variant.opened .bookshelf-glow-1,\n' +
      '.box3d-wrap.bookshelf-variant.opened .bookshelf-glow-2,\n' +
      '.box3d-wrap.bookshelf-variant.opened .bookshelf-glow-3,\n' +
      '.box3d-wrap.bookshelf-variant.opened .bookshelf-glow-4 {\n' +
      '  opacity: 1;\n' +
      '}\n' +
      '\n' +
      '.bookshelf-glow-0 { /* Floor glow */\n' +
      '  position: absolute;\n' +
      '  width: 419px; height: 424px;\n' +
      '  left: calc(50% - 209.5px + 0px);\n' +
      '  top: calc(50% - 212px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(90deg) rotateY(0deg);\n' +
      '  background: radial-gradient(ellipse, rgba(100,200,81,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '}\n' +
      '.bookshelf-glow-1 { /* Cross glow 1 */\n' +
      '  position: absolute;\n' +
      '  width: 419px; height: 424px;\n' +
      '  left: calc(50% - 209.5px + 0px);\n' +
      '  top: calc(50% - 212px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(0deg);\n' +
      '  background: radial-gradient(ellipse, rgba(200,81,168,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '}\n' +
      '.bookshelf-glow-2 { /* Cross glow 2 */\n' +
      '  position: absolute;\n' +
      '  width: 419px; height: 424px;\n' +
      '  left: calc(50% - 209.5px + 0px);\n' +
      '  top: calc(50% - 212px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(60deg);\n' +
      '  background: radial-gradient(ellipse, rgba(81,110,200,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '}\n' +
      '.bookshelf-glow-3 { /* Cross glow 3 */\n' +
      '  position: absolute;\n' +
      '  width: 419px; height: 424px;\n' +
      '  left: calc(50% - 209.5px + 0px);\n' +
      '  top: calc(50% - 212px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(120deg);\n' +
      '  background: radial-gradient(ellipse, rgba(227,2,2,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '}\n' +
      '.bookshelf-glow-4 { /* Item.glow */\n' +
      '  position: absolute;\n' +
      '  width: 419px; height: 424px;\n' +
      '  left: calc(50% - 209.5px + 0px);\n' +
      '  top: calc(50% - 212px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(68deg);\n' +
      '  background: radial-gradient(ellipse, rgba(255,200,80,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '}\n' +
      '/* Glow child: "📚" */\n' +
      '.bookshelf-glow-child-4 {\n' +
      '  position: absolute;\n' +
      '  left: 50%; top: 50%;\n' +
      '  pointer-events: none;\n' +
      '  line-height: 1; white-space: nowrap;\n' +
      '  transition: all 0.4s cubic-bezier(0.33,1,0.68,1);\n' +
      '  text-shadow: 0 0 12px rgba(255,200,80,0.5);\n' +
      '  font-size: 43px;\n' +
      '  opacity: 0.5;\n' +
      '  transform: translate(-50%,-50%) translateY(-83px) translateZ(100px) rotateX(0deg) rotateY(68deg);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant.hovered .bookshelf-glow-child-4 {\n' +
      '  font-size: 57px;\n' +
      '  opacity: 0.63;\n' +
      '  transform: translate(-50%,-50%) translateY(-25px) translateZ(64px) rotateX(0deg) rotateY(21deg);\n' +
      '}\n' +
      '.box3d-wrap.bookshelf-variant.opened .bookshelf-glow-child-4 {\n' +
      '  font-size: 101px;\n' +
      '  opacity: 1;\n' +
      '  transform: translate(-50%,-50%) translateY(-42px) translateZ(105px) rotateX(9deg) rotateY(-16deg);\n' +
      '}\n' +
      '\n' +
      '/* Container fade */\n' +
      '#bookshelf-peek-container { transition: opacity 0.3s ease; }\n';

    var el = document.createElement('style');
    el.textContent = baseCss;
    document.head.appendChild(el);
  }

  // ── Book resolution ─────────────────────────────────────────────

  /**
   * Resolve which book to display at grid position (x, y).
   * Priority: explicit floorData.books assignment → biome random → generic fallback.
   */
  function _resolveBook(fx, fy, floorData) {
    // 1. Check explicit assignment
    var books = floorData.books;
    if (books) {
      for (var i = 0; i < books.length; i++) {
        if (books[i].x === fx && books[i].y === fy) {
          var assigned = _catalogById[books[i].bookId];
          if (assigned) return assigned;
        }
      }
    }

    // 2. Terminal tiles prefer terminal-category entries
    var tile = floorData.grid[fy] ? floorData.grid[fy][fx] : 0;
    if (tile === TILES.TERMINAL && _catalogByCategory && _catalogByCategory['terminal']) {
      var tPool = _catalogByCategory['terminal'];
      if (tPool.length > 0) {
        var tIdx = ((fx * 11 + fy * 17) & 0x7fffffff) % tPool.length;
        return tPool[tIdx];
      }
    }

    // 3. Biome-appropriate random
    var biome = floorData.biome || 'guild';
    var pool = _catalogByBiome[biome];
    if (pool && pool.length > 0) {
      // Seeded-ish: use position as a stable index so same shelf → same book
      var idx = ((fx * 7 + fy * 13) & 0x7fffffff) % pool.length;
      return pool[idx];
    }

    // 4. Any book
    if (_catalog.length > 0) {
      var fallbackIdx = ((fx * 7 + fy * 13) & 0x7fffffff) % _catalog.length;
      return _catalog[fallbackIdx];
    }

    return null;
  }

  // ── DOM builder ────────────────────────────────────────────────────

  function _buildWrap() {
    var w = document.createElement('div');
    w.className = 'box3d-wrap bookshelf-variant';

    // 5 sub-edge children template for structural panes
    var SE = '<div class="sub-edge-back"></div>' +
             '<div class="sub-edge-left"></div>' +
             '<div class="sub-edge-right"></div>' +
             '<div class="sub-edge-top"></div>' +
             '<div class="sub-edge-bottom"></div>';

    w.innerHTML =
      '<div class="box3d-scene">' +
        '<div class="box3d-spin">' +
          '<div class="box3d-body">' +
            '<div class="bf-back"></div>' +
            '<div class="bf-left">' + SE + '</div>' +
            '<div class="bf-right">' + SE + '</div>' +
            '<div class="bf-top">' + SE + '</div>' +
            '<div class="bf-bottom">' + SE + '</div>' +
            '<div class="bf-top-2">' + SE + '</div>' +
            '<div class="bookshelf-glow-0"></div>' +
            '<div class="bookshelf-glow-1"></div>' +
            '<div class="bookshelf-glow-2"></div>' +
            '<div class="bookshelf-glow-3"></div>' +
            '<div class="bookshelf-glow-4"><span class="bookshelf-glow-child-4">📚</span></div>' +
          '</div>' +
        '</div>' +
      '</div>';

    return w;
  }

  // ── Init ───────────────────────────────────────────────────────

  function init() {
    _injectCSS();
    _loadCatalog();

    _container3d = document.getElementById('bookshelf-peek-container');
    if (!_container3d) {
      _container3d = document.createElement('div');
      _container3d.id = 'bookshelf-peek-container';
      _container3d.style.cssText =
        'position:absolute; top:30%; left:50%;' +
        'transform:translate(-50%,-50%) scale(0.75);' +
        'z-index:17; pointer-events:none; opacity:0;' +
        'transition:opacity 0.3s ease;';
      var viewport = document.getElementById('viewport');
      if (viewport) viewport.appendChild(_container3d);
    }

    _labelLayer = document.getElementById('bookshelf-peek-labels');
    if (!_labelLayer) {
      _labelLayer = document.createElement('div');
      _labelLayer.id = 'bookshelf-peek-labels';
      _labelLayer.style.cssText =
        'position:absolute; top:0; left:0; width:100%; height:100%;' +
        'z-index:2; pointer-events:none;';
      _container3d.appendChild(_labelLayer);
    }

    _subLabel = document.getElementById('bookshelf-peek-sublabel');
    if (!_subLabel) {
      _subLabel = document.createElement('div');
      _subLabel.id = 'bookshelf-peek-sublabel';
      _subLabel.style.cssText =
        'position:absolute; top:100%; left:50%; transform:translateX(-50%);' +
        'margin-top:60px; text-align:center;' +
        'font:20px monospace; color:rgba(200,170,100,0);' +
        'text-shadow:0 1px 4px rgba(0,0,0,0.7);' +
        'transition:color 0.4s ease 0.3s; white-space:nowrap;' +
        'pointer-events:none; line-height:1.4;';
      _labelLayer.appendChild(_subLabel);
    }

    _actionBtn = document.getElementById('bookshelf-peek-action');
    if (!_actionBtn) {
      _actionBtn = document.createElement('button');
      _actionBtn.id = 'bookshelf-peek-action';
      _actionBtn.style.cssText =
        'position:absolute; top:100%; left:50%;' +
        'transform:translateX(-50%);' +
        'margin-top:130px; min-height:48px;' +
        'font:bold 18px monospace; color:#dcc8a0;' +
        'background:rgba(100,80,40,0.5);' +
        'border:2px solid rgba(200,170,100,0.4);' +
        'border-radius:8px; padding:12px 28px;' +
        'text-shadow:0 0 8px rgba(200,170,100,0.4);' +
        'cursor:pointer; pointer-events:auto;' +
        'opacity:0; transition:opacity 0.3s ease;' +
        'white-space:nowrap; outline:none;';
      _actionBtn.textContent = 'Read';

      // Hover button → cycle crack animation
      _actionBtn.addEventListener('mouseenter', function () {
        if (_phase >= 1 && _phase < 3 && _wrap) {
          _wrap.classList.add('hovered');
          _phase = 2;
        }
        _actionBtn.style.color = '#fff';
        _actionBtn.style.background = 'rgba(140,120,60,0.6)';
        _actionBtn.style.borderColor = '#dcc8a0';
      });
      _actionBtn.addEventListener('mouseleave', function () {
        if (_phase === 2 && _wrap) {
          _wrap.classList.remove('hovered');
          _phase = 1;
          setTimeout(function () {
            if (_active && _phase === 1 && _wrap) {
              _wrap.classList.add('hovered');
              _phase = 2;
            }
          }, 200);
        }
        _actionBtn.style.color = '#dcc8a0';
        _actionBtn.style.background = 'rgba(100,80,40,0.5)';
        _actionBtn.style.borderColor = 'rgba(200,170,100,0.4)';
      });

      // Phase 3: click button → full open + show book
      _actionBtn.addEventListener('click', function (e) {
        if (e) e.stopPropagation();
        _triggerPhase3();
      });

      _labelLayer.appendChild(_actionBtn);
    }
  }

  // ── Show 3D box (phase 1: closed) ──────────────────────────────────

  function _show3d(fx, fy, floorData) {
    if (_active) return;

    var book = _resolveBook(fx, fy, floorData);
    if (!book) return;

    if (typeof AudioSystem !== 'undefined') AudioSystem.play('ui-popup', { volume: 0.4 });

    _active = true;
    _phase = 1;
    _timer = 0;
    _currentBook = book;
    _currentPage = 0;
    _facingX = fx;
    _facingY = fy;
    _hideTimer = 0;

    // Track this book as read
    if (typeof Player !== 'undefined' && book.id) {
      Player.setFlag('book_read_' + book.id, true);
    }

    // Build and insert 3D box
    _wrap = _buildWrap();
    _wrap.style.zIndex = '1';
    _wrap.style.pointerEvents = 'none';
    _container3d.insertBefore(_wrap, _labelLayer);

    // Initialize label
    if (_subLabel) {
      _subLabel.textContent = book.icon + ' ' + book.title;
      _subLabel.style.color = 'rgba(200,170,100,0)';
    }
    if (_actionBtn) {
      _actionBtn.textContent = book.category === 'terminal' ? 'Access' : 'Read';
      _actionBtn.style.opacity = '0';
    }

    // Fade in
    _container3d.style.opacity = '1';

    // Auto-crack (phase 1→2) after brief settle
    setTimeout(function () {
      if (_active && _phase >= 1) {
        if (_subLabel) _subLabel.style.color = 'rgba(200,170,100,0.9)';
        if (_actionBtn) _actionBtn.style.opacity = '1';
        setTimeout(function () {
          if (_active && _phase === 1 && _wrap) {
            _wrap.classList.add('hovered');
            _phase = 2;
          }
        }, 200);
      }
    }, 150);
  }

  // ── Phase 3: full open + show book ──────────────────────────────────

  function _triggerPhase3() {
    if (_phase === 3 || !_active || !_currentBook) return;

    _phase = 3;

    if (_wrap) {
      _wrap.classList.remove('hovered');
      _wrap.classList.add('opened');
    }

    if (typeof AudioSystem !== 'undefined') {
      AudioSystem.play('ui-confirm', { volume: 0.4 });
    }

    _renderPage();
  }

  // ── Hide ────────────────────────────────────────────────────────

  function _hide() {
    if (!_active) { _timer = 0; return; }

    if (typeof AudioSystem !== 'undefined') AudioSystem.play('ui-click', { volume: 0.3 });

    if (_wrap) {
      _wrap.classList.remove('opened', 'hovered');
    }
    _container3d.style.opacity = '0';
    if (_subLabel) _subLabel.style.color = 'rgba(200,170,100,0)';
    if (_actionBtn) _actionBtn.style.opacity = '0';

    // Close DialogBox if it was ours
    if (_currentBook && typeof DialogBox !== 'undefined' && DialogBox.isOpen()) {
      DialogBox.close();
    }

    setTimeout(function () {
      _destroyWrap();
    }, 400);

    _resetState();
  }

  function _resetState() {
    _active = false;
    _phase = 0;
    _currentBook = null;
    _currentPage = 0;
    _facingX = -1;
    _facingY = -1;
    _hideTimer = 0;
    _timer = 0;
  }

  function _destroyWrap() {
    if (_wrap && _wrap.parentNode) {
      _wrap.parentNode.removeChild(_wrap);
    }
    _wrap = null;
  }

  function _renderPage() {
    if (!_currentBook || typeof DialogBox === 'undefined') return;

    var book = _currentBook;
    var isCRT = book.category === 'terminal' || book.category === 'diagnostic';
    var page = book.pages[_currentPage];
    var pageLabel;
    var navParts = [];

    if (isCRT) {
      // CRT terminal style: green monospace feel, record/entry numbering
      pageLabel = '[RECORD ' + (_currentPage + 1) + '/' + book.pages.length + ']';
      if (_currentPage > 0) navParts.push('[A] << PREV');
      if (_currentPage < book.pages.length - 1) navParts.push('[D] NEXT >>');
      navParts.push('[W/S] SCROLL');
      navParts.push('[BACK] DISCONNECT');
      page = '> ' + page.replace(/\n/g, '\n> '); // CRT prompt prefix
    } else {
      pageLabel = '- Page ' + (_currentPage + 1) + ' of ' + book.pages.length + ' -';
      if (_currentPage > 0) navParts.push('[A] \u2190 Prev');
      if (_currentPage < book.pages.length - 1) navParts.push('[D] Next \u2192');
      navParts.push('[W/S] Scroll');
      navParts.push('[Back] Close');
    }

    var navHint = '\n\n' + navParts.join('   ');

    DialogBox.show({
      speaker: (isCRT ? '\uD83D\uDDA5\uFE0F ' : '') + book.icon + ' ' + book.title,
      text: page + '\n\n' + pageLabel + navHint,
      instant: true,
      priority: 2, // PERSISTENT — stays until explicitly closed
      style: isCRT ? 'terminal' : undefined
    });
  }

  // ── Key handling ────────────────────────────────────────────────

  function handleKey(key) {
    if (!_active || !_currentBook) return false;

    if (key === 'KeyD' || key === 'ArrowRight' || key === 'KeyL') {
      if (_currentPage < _currentBook.pages.length - 1) {
        _currentPage++;
        if (typeof AudioSystem !== 'undefined') AudioSystem.play('page-turn');
        _renderPage();
      }
      return true;
    }
    if (key === 'KeyA' || key === 'ArrowLeft' || key === 'KeyJ') {
      if (_currentPage > 0) {
        _currentPage--;
        if (typeof AudioSystem !== 'undefined') AudioSystem.play('page-turn');
        _renderPage();
      }
      return true;
    }
    // Vertical scroll within a long page (W/S or ArrowUp/ArrowDown).
    // Delegates to DialogBox.scroll which no-ops when the page fits.
    if (key === 'KeyW' || key === 'ArrowUp' || key === 'KeyI') {
      if (typeof DialogBox !== 'undefined' && DialogBox.scroll) {
        DialogBox.scroll(-1);
      }
      return true;
    }
    if (key === 'KeyS' || key === 'ArrowDown' || key === 'KeyK') {
      if (typeof DialogBox !== 'undefined' && DialogBox.scroll) {
        DialogBox.scroll(+1);
      }
      return true;
    }
    if (key === 'PageUp') {
      if (typeof DialogBox !== 'undefined' && DialogBox.scroll) DialogBox.scroll(-5);
      return true;
    }
    if (key === 'PageDown') {
      if (typeof DialogBox !== 'undefined' && DialogBox.scroll) DialogBox.scroll(+5);
      return true;
    }
    if (key === 'Escape') {
      _hide();
      return true;
    }
    return false;
  }

  // ── Update (per-frame) ──────────────────────────────────────────

  function update(dt) {
    if (!MC || typeof FloorManager === 'undefined') return;

    // ── Input edge detection ──
    var IM = (typeof InputManager !== 'undefined') ? InputManager : null;
    var fwdDown = IM ? IM.isDown('step_forward') : false;
    var backDown = IM ? IM.isDown('step_back') : false;
    var fwdEdge = fwdDown && !_prevForward;
    var backEdge = backDown && !_prevBack;
    _prevForward = fwdDown;
    _prevBack = backDown;

    if (_active && backEdge) { _hide(); return; }
    if (_active && fwdEdge && _phase >= 1 && _phase < 3) { _triggerPhase3(); return; }

    var floorData = FloorManager.getFloorData();
    if (!floorData) { if (_active) _hide(); return; }

    var p = Player.getPos();
    var dir = Player.getDir();
    var fx = p.x + MC.DX[dir];
    var fy = p.y + MC.DY[dir];

    // Out of bounds
    if (fx < 0 || fx >= floorData.gridW || fy < 0 || fy >= floorData.gridH) {
      if (_active) {
        _hideTimer += dt;
        if (_hideTimer >= HIDE_DELAY) _hide();
      } else {
        _timer = 0;
      }
      return;
    }

    var tile = floorData.grid[fy][fx];

    if (tile === TILES.BOOKSHELF || tile === TILES.TERMINAL) {
      // Yield to MailboxPeek on shared terminal positions (home mail station).
      // MailboxPeek takes priority — if it's showing, we stay dormant.
      if (typeof MailboxPeek !== 'undefined' && MailboxPeek.isShowing && MailboxPeek.isShowing()) {
        _timer = 0;
        if (_active) _hide();
        return;
      }

      _hideTimer = 0;
      if (_active && fx === _facingX && fy === _facingY) {
        // Already showing this bookshelf/terminal — keep it open
        return;
      }
      // New bookshelf/terminal or not yet active — debounce
      if (!_active || fx !== _facingX || fy !== _facingY) {
        _timer += dt;
        if (_timer >= SHOW_DELAY) {
          if (_active) _hide(); // Close old one first
          _show3d(fx, fy, floorData);
        }
      }
    } else {
      _timer = 0;
      if (_active) {
        _hideTimer += dt;
        if (_hideTimer >= HIDE_DELAY) _hide();
      }
    }
  }

  // ── Public API ──────────────────────────────────────────────────

  function forceHide() { _hide(); }

  return {
    init: init,
    update: update,
    handleKey: handleKey,
    isActive: function () { return _active; },
    getBook: function () { return _currentBook; },
    getPage: function () { return _currentPage; },
    getCatalog: function () { return _catalog; },
    getBookById: function (id) { return _catalogById[id] || null; },
    forceHide: forceHide,

    /**
     * Immediately open the book peek for the bookshelf at (fx, fy).
     * Called by game.js on OK press — bypasses the autonomous 400ms debounce.
     * Advances straight to phase 3 (open + show book).
     * @param {number} fx - Grid x of the BOOKSHELF tile
     * @param {number} fy - Grid y of the BOOKSHELF tile
     * @returns {boolean} true if a book was shown
     */
    tryShow: function (fx, fy) {
      if (_active && fx === _facingX && fy === _facingY) return true; // already showing this one
      if (_active) _hide(); // close a different book first
      var floorData = (typeof FloorManager !== 'undefined') ? FloorManager.getFloorData() : null;
      if (!floorData) return false;
      if (!_loaded) _loadCatalog(); // last-ditch retry if init() missed

      var book = _resolveBook(fx, fy, floorData);
      if (!book) return false;

      _active = true;
      _phase = 3; // Skip animation phases
      _currentBook = book;
      _currentPage = 0;
      _facingX = fx;
      _facingY = fy;
      _hideTimer = 0;
      _timer = 0;

      // Track this book as read
      if (typeof Player !== 'undefined' && book.id) {
        Player.setFlag('book_read_' + book.id, true);
      }

      if (typeof AudioSystem !== 'undefined') AudioSystem.play('page-turn');

      _renderPage();
      return _active;
    },

    /**
     * Check if a bookshelf at grid position (x, y) has any resolvable book.
     * Used by InteractPrompt to show a non-interactive state for empty shelves.
     * @param {number} fx - Grid x
     * @param {number} fy - Grid y
     * @returns {boolean}
     */
    hasBook: function (fx, fy) {
      if (!_loaded) return false;
      var floorData = (typeof FloorManager !== 'undefined') ? FloorManager.getFloorData() : null;
      if (!floorData) return false;
      return !!_resolveBook(fx, fy, floorData);
    },

    /**
     * Register the book catalog from a JS data file (Layer 5).
     * Called by data/books.js at load time — eliminates the XHR dependency
     * that fails silently on file:// in Chromium-based browsers.
     * @param {object} data - The parsed books.json structure ({ books: [...] })
     */
    registerCatalog: function (data) {
      var books = data.books || data || [];
      if (!Array.isArray(books)) books = [];
      _catalog = books;
      _catalogById = {};
      _catalogByBiome = {};
      _catalogByCategory = {};
      for (var i = 0; i < _catalog.length; i++) {
        var book = _catalog[i];
        _catalogById[book.id] = book;
        if (!_catalogByBiome[book.biome]) _catalogByBiome[book.biome] = [];
        _catalogByBiome[book.biome].push(book);
        if (book.category) {
          if (!_catalogByCategory[book.category]) _catalogByCategory[book.category] = [];
          _catalogByCategory[book.category].push(book);
        }
      }
      _loaded = true;
      console.log('[BookshelfPeek] Registered ' + _catalog.length + ' books via script');
    }
  };
})();
