/**
 * ChestPeek — Treasure chest reveal when facing a CHEST tile.
 *
 * 3-phase CSS 3D animation (matches DoorPeek pattern):
 *   Phase 1 (closed):  Player faces CHEST tile. Chest appears closed.
 *   Phase 2 (cracked): Auto-advances ~200ms after show. `.hovered` class added
 *                      (lid rotateX 25°, backpack emoji appears). Labels appear.
 *   Phase 3 (opened):  Forward input / "Loot" button click. `.opened` class added
 *                      (lid rotateX 135°, emoji rises, glows appear). Fires game action.
 *
 * Lifecycle integration: Reads from CrateSystem for phase (loot/empty/restocked/stash)
 * and shows appropriate sub-labels and button text.
 *
 * Self-contained CSS 3D — no BoxAnim dependency.
 *
 * Layer 3.5 (after CratePeek if exists, after InteractPrompt)
 * Depends on: TILES, Player, MovementController, FloorManager, CrateSystem,
 *             DayCycle, InputManager (for forward/back edge detection)
 */
var ChestPeek = (function () {
  'use strict';

  var MC = (typeof MovementController !== 'undefined') ? MovementController : null;

  // ── Config ──────────────────────────────────────────────────────
  var SHOW_DELAY = 300;     // ms before box appears (debounce)
  var AUTO_CRACK_DELAY = 200; // ms after show before phase 2

  // ── State ──────────────────────────────────────────────────────
  var _active      = false;
  var _phase       = 0;     // 0=inactive, 1=closed, 2=hovered-crack, 3=opened
  var _facingTile  = 0;
  var _facingX     = -1;
  var _facingY     = -1;
  var _timer       = 0;
  var _container   = null;
  var _wrap        = null;
  var _subLabel    = null;
  var _actionBtn   = null;
  var _styleInjected = false;

  // Forward/back edge tracking
  var _prevForward = false;
  var _prevBack    = false;

  // ── CSS Injection ────────────────────────────────────────────────

  function _injectCSS() {
    if (_styleInjected) return;
    _styleInjected = true;

    // Chest variant CSS from BoxForge v1.0 — lines 1-414 from /tmp/chest_css.js
    var css =
      '/* === Variant: chest (510x193, depth 228) === */\n' +
      '/* Generated by BoxForge v1.0 — 6 panes (4 struct, 1 lid, 1 extra) */\n' +
      '\n' +
      '.box3d-wrap.chest-variant {\n' +
      '  --chest-w: 510px;\n' +
      '  --chest-h: 193px;\n' +
      '  --box-d: 114px;\n' +
      '  --box-half: -114px;\n' +
      '  --bevel-w: 2px;\n' +
      '  --box-dark: #3d2b08;\n' +
      '  --box-dark2: #1f0d00;\n' +
      '  --box-light: #a87830;\n' +
      '  --box-floor: #1a1206;\n' +
      '  --box-ceil: #5a4020;\n' +
      '  --box-glow: rgba(255,200,80,0.6);\n' +
      '  --perspective: 352px;\n' +
      '  perspective: 352px;\n' +
      '  width: 510px;\n' +
      '  height: 193px;\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-scene {\n' +
      '  width: 510px; height: 193px;\n' +
      '  transform: rotateX(-28deg) rotateY(-5deg);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-spin {\n' +
      '  width: 510px; height: 193px;\n' +
      '}\n' +
      '.chest-variant .box3d-body {\n' +
      '  width: 510px; height: 193px;\n' +
      '}\n' +
      '\n' +
      '/* Back (back): 510 x 193 */\n' +
      '.box3d-wrap.chest-variant .bf-back {\n' +
      '  width: 510px; height: 193px;\n' +
      '  background: linear-gradient(to top, #3d2b08, #a87830);\n' +
      '  transform: translateZ(-114px) translate(0px,0px);\n' +
      '}\n' +
      '/* Left (left): 228 x 193 */\n' +
      '.box3d-wrap.chest-variant .bf-left {\n' +
      '  width: 228px; height: 193px;\n' +
      '  left: 141px; top: 0px;\n' +
      '  background: linear-gradient(to top, #3d2b08, #a87830);\n' +
      '  transform: translate(-253px,1px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '/* Sub-box: depth 4px */\n' +
      '.box3d-wrap.chest-variant .bf-left { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.chest-variant .bf-left > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 228px; height: 193px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-4px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-left > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 8px; height: 193px;\n' +
      '  left: 110px; top: 0px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-114px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-left > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 8px; height: 193px;\n' +
      '  left: 110px; top: 0px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(114px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-left > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 228px; height: 8px;\n' +
      '  left: 0px; top: 92.5px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(96.5px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-left > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 228px; height: 8px;\n' +
      '  left: 0px; top: 92.5px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-96.5px) translateY(0px);\n' +
      '}\n' +
      '/* Right (right): 228 x 193 */\n' +
      '.box3d-wrap.chest-variant .bf-right {\n' +
      '  width: 228px; height: 193px;\n' +
      '  left: 141px; top: 0px;\n' +
      '  background: linear-gradient(to top, #3d2b08, #a87830);\n' +
      '  transform: translate(256px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '/* Sub-box: depth 4px */\n' +
      '.box3d-wrap.chest-variant .bf-right { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.chest-variant .bf-right > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 228px; height: 193px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-4px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-right > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 8px; height: 193px;\n' +
      '  left: 110px; top: 0px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-114px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-right > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 8px; height: 193px;\n' +
      '  left: 110px; top: 0px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(114px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-right > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 228px; height: 8px;\n' +
      '  left: 0px; top: 92.5px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(96.5px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-right > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 228px; height: 8px;\n' +
      '  left: 0px; top: 92.5px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-96.5px) translateY(0px);\n' +
      '}\n' +
      '/* Bottom (bottom): 510 x 228 */\n' +
      '.box3d-wrap.chest-variant .bf-bottom {\n' +
      '  width: 510px; height: 228px;\n' +
      '  left: 0px; top: -17.5px;\n' +
      '  background: linear-gradient(to top, #3d2b08, #a87830);\n' +
      '  transform: translate(0px,-1.5px) rotateX(90deg) translateZ(-96.5px) translateY(0px);\n' +
      '}\n' +
      '\n' +
      '/* Lid: Lid (510x230, hinge: top, open: 135°, hover: 25°) */\n' +
      '.box3d-wrap.chest-variant .box3d-lid-wrap {\n' +
      '  position: absolute; transform-style: preserve-3d;\n' +
      '  width: 510px; height: 230px;\n' +
      '  left: 0px; top: -18.5px;\n' +
      '  transform: translate(0px,10px) rotateX(90deg) translateZ(96.5px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid {\n' +
      '  width: 510px; height: 230px;\n' +
      '  background: linear-gradient(to top, #3d2b08, #a87830);\n' +
      '  transform-origin: center 0px;\n' +
      '  transition: transform 0.4s cubic-bezier(0.33, 1, 0.68, 1);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant.hovered .box3d-lid {\n' +
      '  transform: rotateX(25deg);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant.opened .box3d-lid {\n' +
      '  transform: rotateX(135deg);\n' +
      '}\n' +
      '/* Sub-box: depth 12px */\n' +
      '.box3d-wrap.chest-variant .box3d-lid { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 510px; height: 230px;\n' +
      '  background: linear-gradient(to top, #a87a3f, #c6985d);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-12px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 24px; height: 230px;\n' +
      '  left: 243px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a87a3f, #c6985d);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-255px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 24px; height: 230px;\n' +
      '  left: 243px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a87a3f, #c6985d);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(255px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 510px; height: 24px;\n' +
      '  left: 0px; top: 103px;\n' +
      '  background: linear-gradient(to top, #a87a3f, #c6985d);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(115px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 510px; height: 24px;\n' +
      '  left: 0px; top: 103px;\n' +
      '  background: linear-gradient(to top, #a87a3f, #c6985d);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-115px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-child-0 {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 504px; height: 225px;\n' +
      '  left: 3px; top: 2.5px;\n' +
      '  background: linear-gradient(to top, #3d2b08, #a87830);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(11px) translate(-2px,-2px);\n' +
      '}\n' +
      '/* Sub-box: depth 60px */\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-child-0 { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-child-0 > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 504px; height: 225px;\n' +
      '  background: linear-gradient(to top, #6c3e02, #8a5c20);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-60px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-child-0 > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 120px; height: 225px;\n' +
      '  left: 192px; top: 0px;\n' +
      '  background: linear-gradient(to top, #6c3e02, #8a5c20);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-252px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-child-0 > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 120px; height: 225px;\n' +
      '  left: 192px; top: 0px;\n' +
      '  background: linear-gradient(to top, #6c3e02, #8a5c20);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(252px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-child-0 > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 504px; height: 120px;\n' +
      '  left: 0px; top: 52.5px;\n' +
      '  background: linear-gradient(to top, #6c3e02, #8a5c20);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(112.5px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .box3d-lid > .sub-child-0 > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 504px; height: 120px;\n' +
      '  left: 0px; top: 52.5px;\n' +
      '  background: linear-gradient(to top, #6c3e02, #8a5c20);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-112.5px) translateY(0px);\n' +
      '}\n' +
      '\n' +
      '/* === EXTRA PANES (1) === */\n' +
      '/* Front (front, 509x190, role: structure) */\n' +
      '.box3d-wrap.chest-variant .bf-front {\n' +
      '  width: 509px; height: 190px;\n' +
      '  left: 0.5px; top: 1.5px;\n' +
      '  transform: translateZ(114px) translate(1px,-1px);\n' +
      '  background: linear-gradient(to top, #3d2b08, #a87830);\n' +
      '}\n' +
      '/* Sub-box: depth 3px */\n' +
      '.box3d-wrap.chest-variant .bf-front { transform-style: preserve-3d; }\n' +
      '.box3d-wrap.chest-variant .bf-front > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 509px; height: 190px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-3px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-front > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 6px; height: 190px;\n' +
      '  left: 251.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-254.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-front > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 6px; height: 190px;\n' +
      '  left: 251.5px; top: 0px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(254.5px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-front > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 509px; height: 6px;\n' +
      '  left: 0px; top: 92px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(95px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant .bf-front > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 509px; height: 6px;\n' +
      '  left: 0px; top: 92px;\n' +
      '  background: linear-gradient(to top, #8a5a12, #a87830);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-95px) translateY(0px);\n' +
      '}\n' +
      '\n' +
      '/* === GLOW SOURCES (5) === */\n' +
      '.chest-glow-0 { /* Floor glow */\n' +
      '  position: absolute;\n' +
      '  width: 714px; height: 270px;\n' +
      '  left: calc(50% - 357px + 0px);\n' +
      '  top: calc(50% - 135px + 107px);\n' +
      '  transform: translateZ(0px) rotateX(90deg) rotateY(0deg);\n' +
      '  background: radial-gradient(ellipse, rgba(200,80,198,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '}\n' +
      '.chest-glow-1 { /* Cross glow 1 */\n' +
      '  position: absolute;\n' +
      '  width: 714px; height: 270px;\n' +
      '  left: calc(50% - 357px + 0px);\n' +
      '  top: calc(50% - 135px + -104px);\n' +
      '  transform: translateZ(0px) rotateX(86deg) rotateY(-1deg);\n' +
      '  background: radial-gradient(ellipse, rgba(200,80,198,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '}\n' +
      '.chest-glow-2 { /* Cross glow 2 */\n' +
      '  position: absolute;\n' +
      '  width: 714px; height: 270px;\n' +
      '  left: calc(50% - 357px + 0px);\n' +
      '  top: calc(50% - 135px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(25deg);\n' +
      '  background: radial-gradient(ellipse, rgba(200,80,198,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '}\n' +
      '.chest-glow-3 { /* Cross glow 3 */\n' +
      '  position: absolute;\n' +
      '  width: 714px; height: 270px;\n' +
      '  left: calc(50% - 357px + 0px);\n' +
      '  top: calc(50% - 135px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(-23deg);\n' +
      '  background: radial-gradient(ellipse, rgba(200,80,198,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '}\n' +
      '.chest-glow-4 { /* Item.glow */\n' +
      '  position: absolute;\n' +
      '  width: 714px; height: 270px;\n' +
      '  left: calc(50% - 357px + 0px);\n' +
      '  top: calc(50% - 135px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(68deg);\n' +
      '  background: radial-gradient(ellipse, rgba(255,200,80,0.05) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '}\n' +
      '/* Glow child: "🎒" emoji */\n' +
      '.chest-glow-child-4 {\n' +
      '  position: absolute;\n' +
      '  left: 50%; top: 50%;\n' +
      '  pointer-events: none;\n' +
      '  line-height: 1; white-space: nowrap;\n' +
      '  transition: all 0.4s cubic-bezier(0.33,1,0.68,1);\n' +
      '  text-shadow: 0 0 12px rgba(255,200,80,0.5);\n' +
      '  font-size: 0px;\n' +
      '  opacity: 0;\n' +
      '  transform: translate(-50%,-50%) translateY(-50px) translateZ(0px) rotateX(0deg) rotateY(68deg);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant.hovered .chest-glow-child-4 {\n' +
      '  font-size: 98px;\n' +
      '  opacity: 1;\n' +
      '  transform: translate(-50%,-50%) translateY(-39px) translateZ(9px) rotateX(-4deg) rotateY(23deg);\n' +
      '}\n' +
      '.box3d-wrap.chest-variant.opened .chest-glow-child-4 {\n' +
      '  font-size: 120px;\n' +
      '  opacity: 1;\n' +
      '  transform: translate(-50%,-50%) translateY(-139px) translateZ(30px) rotateX(6deg) rotateY(-16deg);\n' +
      '}\n' +
      '\n' +
      '/* Glow visibility */\n' +
      '.chest-glow-0,.chest-glow-1,.chest-glow-2,.chest-glow-3,.chest-glow-4 {\n' +
      '  opacity: 0; transition: opacity 0.4s ease 0.15s;\n' +
      '}\n' +
      '.box3d-wrap.chest-variant.opened .chest-glow-0,\n' +
      '.box3d-wrap.chest-variant.opened .chest-glow-1,\n' +
      '.box3d-wrap.chest-variant.opened .chest-glow-2,\n' +
      '.box3d-wrap.chest-variant.opened .chest-glow-3,\n' +
      '.box3d-wrap.chest-variant.opened .chest-glow-4 {\n' +
      '  opacity: 1;\n' +
      '}\n' +
      '\n' +
      '/* Container fade */\n' +
      '#chest-peek-container { transition: opacity 0.3s ease; }\n';

    var el = document.createElement('style');
    el.textContent = css;
    document.head.appendChild(el);
  }

  // ── DOM builder ────────────────────────────────────────────────────

  function _buildWrap() {
    var w = document.createElement('div');
    w.className = 'box3d-wrap chest-variant';

    // 5 sub-edge children template
    var SE = '<div class="sub-edge-back"></div>' +
             '<div class="sub-edge-left"></div>' +
             '<div class="sub-edge-right"></div>' +
             '<div class="sub-edge-top"></div>' +
             '<div class="sub-edge-bottom"></div>';

    w.innerHTML =
      '<div class="box3d-scene">' +
        '<div class="box3d-spin">' +
          '<div class="box3d-body">' +
            '<div class="bf-back"></div>' +
            '<div class="bf-left">' + SE + '</div>' +
            '<div class="bf-right">' + SE + '</div>' +
            '<div class="bf-bottom"></div>' +
            '<div class="bf-front">' + SE + '</div>' +
            '<div class="box3d-lid-wrap">' +
              '<div class="box3d-lid">' + SE +
                '<div class="sub-child-0">' + SE + '</div>' +
              '</div>' +
            '</div>' +
            '<div class="chest-glow-0"></div>' +
            '<div class="chest-glow-1"></div>' +
            '<div class="chest-glow-2"></div>' +
            '<div class="chest-glow-3"></div>' +
            '<div class="chest-glow-4">' +
              '<div class="chest-glow-child-4">🎒</div>' +
            '</div>' +
          '</div>' +
        '</div>' +
      '</div>';

    return w;
  }

  // ── Init ───────────────────────────────────────────────────────

  function init() {
    _injectCSS();

    _container = document.getElementById('chest-peek-container');
    if (!_container) {
      _container = document.createElement('div');
      _container.id = 'chest-peek-container';
      _container.style.cssText =
        'position:absolute; top:40%; left:50%;' +
        'transform:translate(-50%,-50%);' +
        'z-index:18; pointer-events:none; opacity:0;';
      var viewport = document.getElementById('viewport');
      if (viewport) viewport.appendChild(_container);
    }

    _subLabel = document.getElementById('chest-peek-sublabel');
    if (!_subLabel) {
      _subLabel = document.createElement('div');
      _subLabel.id = 'chest-peek-sublabel';
      _subLabel.style.cssText =
        'position:absolute; top:100%; left:50%; transform:translateX(-50%);' +
        'margin-top:60px; text-align:center;' +
        'font:20px monospace; color:rgba(255,210,100,0);' +
        'text-shadow:0 1px 4px rgba(0,0,0,0.8);' +
        'transition:color 0.4s ease 0.3s; white-space:nowrap;' +
        'pointer-events:none; line-height:1.3;';
      _container.appendChild(_subLabel);
    }

    _actionBtn = document.getElementById('chest-peek-action');
    if (!_actionBtn) {
      _actionBtn = document.createElement('button');
      _actionBtn.id = 'chest-peek-action';
      _actionBtn.style.cssText =
        'position:absolute; top:100%; left:50%;' +
        'transform:translateX(-50%);' +
        'margin-top:130px; min-height:48px;' +
        'font:bold 18px monospace; color:#dcc8a0;' +
        'background:rgba(100,80,40,0.5);' +
        'border:2px solid rgba(200,170,100,0.4);' +
        'border-radius:8px; padding:12px 28px;' +
        'text-shadow:0 0 8px rgba(200,170,100,0.4);' +
        'cursor:pointer; pointer-events:auto;' +
        'opacity:0; transition:opacity 0.3s ease;' +
        'white-space:nowrap; outline:none;';
      _actionBtn.textContent = 'Loot';

      // Hover button → crack animation
      _actionBtn.addEventListener('mouseenter', function () {
        if (_phase >= 1 && _phase < 3 && _wrap) {
          _wrap.classList.add('hovered');
          _phase = 2;
        }
        _actionBtn.style.color = '#fff';
        _actionBtn.style.background = 'rgba(140,120,60,0.6)';
        _actionBtn.style.borderColor = '#dcc8a0';
      });
      _actionBtn.addEventListener('mouseleave', function () {
        if (_phase === 2 && _wrap) {
          _wrap.classList.remove('hovered');
          _phase = 1;
          setTimeout(function () {
            if (_active && _phase === 1 && _wrap) {
              _wrap.classList.add('hovered');
              _phase = 2;
            }
          }, 200);
        }
        _actionBtn.style.color = '#dcc8a0';
        _actionBtn.style.background = 'rgba(100,80,40,0.5)';
        _actionBtn.style.borderColor = 'rgba(200,170,100,0.4)';
      });

      // Phase 3: click button → full open
      _actionBtn.addEventListener('click', function (e) {
        if (e) e.stopPropagation();
        _triggerPhase3();
      });

      _container.appendChild(_actionBtn);
    }
  }

  // ── Phase 3: full open + fire Game.interact() ──────────────────────

  function _triggerPhase3() {
    if (_phase === 3 || !_active) return;

    _phase = 3;

    if (_wrap) {
      _wrap.classList.remove('hovered');
      _wrap.classList.add('opened');
    }

    // UI feedback
    if (typeof AudioSystem !== 'undefined') {
      AudioSystem.play('ui-confirm', { volume: 0.4 });
    }

    // Fire interaction via Game.interact()
    setTimeout(function () {
      if (typeof Game !== 'undefined' && Game.interact) {
        Game.interact(_facingX, _facingY);
      }
      _hide();
    }, 400);
  }

  // ── Per-frame check ──────────────────────────────────────────

  function update(dt) {
    if (!_container) return;
    if (!MC) MC = (typeof MovementController !== 'undefined') ? MovementController : null;
    if (!MC) return;
    if (typeof FloorManager === 'undefined') return;

    // Input edge detection
    var IM = (typeof InputManager !== 'undefined') ? InputManager : null;
    var fwdDown = IM ? IM.isDown('step_forward') : false;
    var backDown = IM ? IM.isDown('step_back') : false;
    var fwdEdge = fwdDown && !_prevForward;
    var backEdge = backDown && !_prevBack;
    _prevForward = fwdDown;
    _prevBack = backDown;

    if (_active && backEdge) { _hide(); return; }
    if (_active && fwdEdge && _phase >= 1) { _triggerPhase3(); return; }

    var floorData = FloorManager.getFloorData();
    if (!floorData) { _hide(); return; }

    var p   = Player.getPos();
    var dir = Player.getDir();
    var fx  = p.x + MC.DX[dir];
    var fy  = p.y + MC.DY[dir];

    if (fx < 0 || fx >= floorData.gridW || fy < 0 || fy >= floorData.gridH) {
      _hide(); return;
    }

    var tile = floorData.grid[fy][fx];
    if (tile !== TILES.CHEST) { _hide(); return; }

    // Same tile we were already peeking at
    if (_active && _facingTile === tile && _facingX === fx && _facingY === fy) {
      return;
    }

    // New tile — accumulate debounce
    _facingTile = tile;
    _facingX = fx;
    _facingY = fy;
    _timer += dt;

    if (_timer >= SHOW_DELAY) {
      _show(tile, fx, fy, floorData);
    }
  }

  // ── Show (phase 1: closed) ──────────────────────────────────

  function _show(tile, fx, fy, floorData) {
    if (_active) _destroyWrap();

    if (typeof AudioSystem !== 'undefined') AudioSystem.play('ui-popup', { volume: 0.4 });

    _active = true;
    _phase = 1;
    _timer = 0;

    // CrateSystem integration for lifecycle phase
    var _phase_lc = 'loot';
    var _chestContainer = null;
    var chestFloorId = FloorManager.getCurrentFloorId();
    if (typeof CrateSystem !== 'undefined') {
      _phase_lc = CrateSystem.getPhase(fx, fy, chestFloorId) || 'loot';
      _chestContainer = CrateSystem.getContainer(fx, fy, chestFloorId);
    }

    // Sub-label text based on lifecycle phase
    var _subText;
    switch (_phase_lc) {
      case 'empty':
        // D3+ chests: restock via deposit. D1/D2 non-home: show days until rehydration.
        if (_chestContainer && _chestContainer.demandRefill) {
          _subText = '\u2192 restock';
        } else if (_chestContainer && _chestContainer.lootedDay !== null &&
                   typeof DayCycle !== 'undefined') {
          var _daysLeft = (_chestContainer.lootedDay + CrateSystem.REHYDRATE_COOLDOWN)
                        - DayCycle.getDay();
          _subText = _daysLeft > 0
            ? '\u231B refills in ' + _daysLeft + ' day' + (_daysLeft > 1 ? 's' : '')
            : '\u2014 empty';
        } else {
          _subText = '\u2014 empty';
        }
        break;
      case 'restocked':  _subText = '\u2714 restocked'; break;
      case 'stash':      _subText = '\u2192 storage';   break;
      default:           _subText = '\u2192 take loot';  break;
    }

    // Build DOM
    _wrap = _buildWrap();
    _wrap.style.zIndex = '1';
    _wrap.style.pointerEvents = 'none';
    _container.insertBefore(_wrap, _subLabel);

    _wrap.style.setProperty('--box-glow', 'rgba(255,200,80,0.6)');

    // Sub-label
    if (_subLabel) {
      _subLabel.textContent = '';
      _subLabel.appendChild(document.createTextNode('treasure chest'));
      _subLabel.appendChild(document.createElement('br'));
      _subLabel.appendChild(document.createTextNode(_subText));
      _subLabel.style.color = 'rgba(255,210,100,0)';
    }

    // Action button
    if (_actionBtn) {
      _actionBtn.style.opacity = '0';
      _actionBtn.style.display = '';
      var btnLabel;
      switch (_phase_lc) {
        case 'empty':
          btnLabel = _chestContainer && _chestContainer.demandRefill ? 'Restock' : 'Empty';
          break;
        case 'restocked': btnLabel = 'Collect'; break;
        case 'stash':     btnLabel = 'Access'; break;
        default:          btnLabel = 'Loot'; break;
      }
      _actionBtn.textContent = btnLabel;
      _actionBtn.style.color = '#dcc8a0';
      _actionBtn.style.background = 'rgba(100,80,40,0.5)';
      _actionBtn.style.borderColor = 'rgba(200,170,100,0.4)';
      _actionBtn.style.textShadow = '0 0 8px rgba(200,170,100,0.4)';
    }

    // Fade in
    _container.style.opacity = '1';

    // Auto-crack (phase 1→2) after brief settle
    setTimeout(function () {
      if (_active && _phase >= 1) {
        if (_subLabel) _subLabel.style.color = 'rgba(255,210,100,0.9)';
        if (_actionBtn) _actionBtn.style.opacity = '1';
        // Auto-advance to phase 2
        setTimeout(function () {
          if (_active && _phase === 1 && _wrap) {
            _wrap.classList.add('hovered');
            _phase = 2;
          }
        }, 200);
      }
    }, 150);
  }

  // ── Hide ──────────────────────────────────────────────────────

  function _hide() {
    if (!_active) { _timer = 0; return; }

    if (typeof AudioSystem !== 'undefined') AudioSystem.play('ui-click', { volume: 0.3 });

    if (_wrap) {
      _wrap.classList.remove('opened', 'hovered');
    }
    _container.style.opacity = '0';
    if (_subLabel) _subLabel.style.color = 'rgba(255,210,100,0)';
    if (_actionBtn) _actionBtn.style.opacity = '0';

    setTimeout(function () {
      _destroyWrap();
    }, 400);

    _resetState();
  }

  function _resetState() {
    _active = false;
    _phase = 0;
    _facingTile = 0;
    _facingX = -1;
    _facingY = -1;
    _timer = 0;
  }

  function _destroyWrap() {
    if (_wrap && _wrap.parentNode) {
      _wrap.parentNode.removeChild(_wrap);
    }
    _wrap = null;
  }

  // ── Public API ─────────────────────────────────────────────────

  function forceHide() { _hide(); }

  return Object.freeze({
    init: init,
    update: update,
    forceHide: forceHide,
    isActive: function () { return _active; },
    handleKey: function () {},
    getPhase: function () { return _phase; }
  });
})();
