/**
 * CratePeek — Self-contained crate reveal for breakable tiles.
 *
 * When the player faces a BREAKABLE tile, a CSS 3D crate box appears
 * centred in the viewport. The lid slides right to reveal the crate
 * interior. 3-phase animation matches DoorPeek pattern.
 *
 * Phase 1 (closed): Player faces BREAKABLE. Crate appears closed.
 * Phase 2 (hover-crack): Auto-advances ~200ms. Lid slides 17%, labels appear.
 * Phase 3 (opened): Forward input or action button. Lid slides 100%, glow shows.
 *
 * Visual: CSS 3D crate variant — wood plank faces, cross-grain lid,
 * warm amber interior glow.
 *
 * Self-contained — no BoxAnim dependency. Embeds all CSS 3D transforms.
 *
 * Layer 3.5 (after InteractPrompt)
 * Depends on: TILES, Player, MovementController, FloorManager, InputManager,
 *             CrateSystem, AudioSystem, Game
 */
var CratePeek = (function () {
  'use strict';

  var MC = typeof MovementController !== 'undefined' ? MovementController : null;

  // ── Config ──────────────────────────────────────────────────────
  var SHOW_DELAY = 400;   // ms before box appears (debounce)

  // ── State ──────────────────────────────────────────────────────
  var _active     = false;
  var _phase      = 0;     // 0=inactive, 1=closed, 2=hover-crack, 3=opened
  var _facingTile = 0;
  var _facingX    = -1;
  var _facingY    = -1;
  var _timer      = 0;
  var _container  = null;
  var _wrap       = null;
  var _labelLayer = null;  // Flat overlay above 3D scene for labels
  var _innerLabel = null;  // "? LOOT ?" text
  var _subLabel   = null;  // Type + hint
  var _actionBtn  = null;  // Visible click target
  var _closeBtn   = null;  // [BACK] Close
  var _styleInjected = false;

  // Forward/back edge tracking (CratePeek runs after InputPoll)
  var _prevForward = false;
  var _prevBack    = false;

  // ── CSS Injection ────────────────────────────────────────────────

  function _injectCSS() {
    if (_styleInjected) return;
    _styleInjected = true;

    var css =
      '/* === Variant: crate (416x346, depth 336) === */\n' +
      '/* Generated by BoxForge v1.0 — 6 panes (5 struct, 1 lid, 0 extra) */\n' +
      '\n' +
      '.box3d-wrap.crate-variant {\n' +
      '  --crate-w: 416px;\n' +
      '  --crate-h: 346px;\n' +
      '  --box-d: 168px;\n' +
      '  --box-half: -168px;\n' +
      '  --bevel-w: 2px;\n' +
      '  --box-dark: #5a3a0a;\n' +
      '  --box-dark2: #3c1c00;\n' +
      '  --box-light: #c49a40;\n' +
      '  --box-floor: #3a2808;\n' +
      '  --box-ceil: #8a6020;\n' +
      '  --box-glow: rgba(200,160,60,0.6);\n' +
      '  --perspective: 802px;\n' +
      '  perspective: 802px;\n' +
      '  width: 416px;\n' +
      '  height: 346px;\n' +
      '  position: relative;\n' +
      '  transform-style: preserve-3d;\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-scene {\n' +
      '  width: 416px; height: 346px;\n' +
      '  transform: rotateX(-18deg) rotateY(-10deg);\n' +
      '  transform-style: preserve-3d;\n' +
      '  position: relative;\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-spin {\n' +
      '  width: 416px; height: 346px;\n' +
      '  transform-style: preserve-3d;\n' +
      '  position: relative;\n' +
      '}\n' +
      '.crate-variant .box3d-body {\n' +
      '  width: 416px; height: 346px;\n' +
      '  transform-style: preserve-3d;\n' +
      '  position: relative;\n' +
      '}\n' +
      '\n' +
      '/* Back (back): 416 x 346 */\n' +
      '.box3d-wrap.crate-variant .bf-back {\n' +
      '  width: 416px; height: 346px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  transform: translateZ(-168px) translate(0px,0px);\n' +
      '  position: absolute; transform-style: preserve-3d;\n' +
      '}\n' +
      '/* Left (left): 336 x 346 */\n' +
      '.box3d-wrap.crate-variant .bf-left {\n' +
      '  width: 336px; height: 346px;\n' +
      '  left: 40px; top: 0px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  transform: translate(-207px,0px) rotateY(90deg) translateZ(0px);\n' +
      '  position: absolute; transform-style: preserve-3d;\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-left > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 336px; height: 346px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-6px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-left > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 346px;\n' +
      '  left: 162px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-168px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-left > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 346px;\n' +
      '  left: 162px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(168px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-left > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 336px; height: 12px;\n' +
      '  left: 0px; top: 167px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(173px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-left > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 336px; height: 12px;\n' +
      '  left: 0px; top: 167px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-173px) translateY(0px);\n' +
      '}\n' +
      '/* Right (right): 336 x 346 */\n' +
      '.box3d-wrap.crate-variant .bf-right {\n' +
      '  width: 336px; height: 346px;\n' +
      '  left: 40px; top: 0px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  transform: translate(208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '  position: absolute; transform-style: preserve-3d;\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-right > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 336px; height: 346px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-6px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-right > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 346px;\n' +
      '  left: 162px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-168px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-right > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 346px;\n' +
      '  left: 162px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(168px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-right > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 336px; height: 12px;\n' +
      '  left: 0px; top: 167px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(173px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-right > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 336px; height: 12px;\n' +
      '  left: 0px; top: 167px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-173px) translateY(0px);\n' +
      '}\n' +
      '/* Top (top): 416 x 342 */\n' +
      '.box3d-wrap.crate-variant .bf-top {\n' +
      '  width: 416px; height: 342px;\n' +
      '  left: 0px; top: 2px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  transform: translate(-1px,13px) rotateX(90deg) translateZ(173px) translateY(0px);\n' +
      '  position: absolute; transform-style: preserve-3d;\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 342px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-11px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 22px; height: 342px;\n' +
      '  left: 197px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 22px; height: 342px;\n' +
      '  left: 197px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 22px;\n' +
      '  left: 0px; top: 160px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(171px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 22px;\n' +
      '  left: 0px; top: 160px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-171px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-0 {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 30px;\n' +
      '  left: 0px; top: 156px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(3px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-0 > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 30px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-14px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-0 > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 28px; height: 30px;\n' +
      '  left: 194px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-0 > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 28px; height: 30px;\n' +
      '  left: 194px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-0 > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 28px;\n' +
      '  left: 0px; top: 1px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(15px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-0 > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 28px;\n' +
      '  left: 0px; top: 1px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-15px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-1 {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 30px;\n' +
      '  left: 0px; top: 156px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(3px) translate(0px,-122px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-1 > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 30px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-5px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-1 > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 10px; height: 30px;\n' +
      '  left: 203px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-1 > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 10px; height: 30px;\n' +
      '  left: 203px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-1 > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 10px;\n' +
      '  left: 0px; top: 10px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(15px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-top > .sub-child-1 > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 10px;\n' +
      '  left: 0px; top: 10px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-15px) translateY(0px);\n' +
      '}\n' +
      '/* Bottom (bottom): 416 x 336 */\n' +
      '.box3d-wrap.crate-variant .bf-bottom {\n' +
      '  width: 416px; height: 336px;\n' +
      '  left: 0px; top: 5px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  transform: translate(0px,-16px) rotateX(90deg) translateZ(-173px) translateY(0px);\n' +
      '  position: absolute; transform-style: preserve-3d;\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-bottom > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 336px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-6px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-bottom > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 336px;\n' +
      '  left: 202px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-bottom > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 12px; height: 336px;\n' +
      '  left: 202px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(208px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-bottom > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 12px;\n' +
      '  left: 0px; top: 162px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(168px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .bf-bottom > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 12px;\n' +
      '  left: 0px; top: 162px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-168px) translateY(0px);\n' +
      '}\n' +
      '\n' +
      '/* Lid: Crate Lid (418x336, hinge: slide-right, open: 104deg, hover: 17deg) */\n' +
      '.box3d-wrap.crate-variant .box3d-lid-wrap {\n' +
      '  position: absolute; transform-style: preserve-3d;\n' +
      '  width: 418px; height: 336px;\n' +
      '  left: -1px; top: 5px;\n' +
      '  transform: translateZ(168px) translate(-1px,-4px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid {\n' +
      '  width: 418px; height: 336px;\n' +
      '  background: repeating-linear-gradient(0deg, #c49a40 0px, #c49a40 8px, #a67c22 8px, #a67c22 9px);\n' +
      '  transform-origin: center center;\n' +
      '  transition: transform 0.4s cubic-bezier(0.33, 1, 0.68, 1);\n' +
      '  position: relative; transform-style: preserve-3d;\n' +
      '}\n' +
      '.box3d-wrap.crate-variant.hovered .box3d-lid {\n' +
      '  transform: translateX(17%);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant.opened .box3d-lid {\n' +
      '  transform: translateX(100%);\n' +
      '}\n' +
      '/* Lid sub-edges and children */\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-edge-back {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 418px; height: 336px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(-15px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-edge-left {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 30px; height: 336px;\n' +
      '  left: 194px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(-209px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-edge-right {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 30px; height: 336px;\n' +
      '  left: 194px; top: 0px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(209px,0px) rotateY(90deg) translateZ(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-edge-top {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 418px; height: 30px;\n' +
      '  left: 0px; top: 153px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(168px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-edge-bottom {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 418px; height: 30px;\n' +
      '  left: 0px; top: 153px;\n' +
      '  background: linear-gradient(to top, #a67c22, #c49a40);\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translate(0px,0px) rotateX(90deg) translateZ(-168px) translateY(0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-child-0 {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 30px;\n' +
      '  left: 1px; top: 153px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(3px) translate(0px,-90px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-child-1 {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 39px;\n' +
      '  left: 1px; top: 148.5px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(1px) translate(0px,0px);\n' +
      '}\n' +
      '.box3d-wrap.crate-variant .box3d-lid > .sub-child-2 {\n' +
      '  position: absolute; pointer-events: none;\n' +
      '  width: 416px; height: 30px;\n' +
      '  left: 1px; top: 153px;\n' +
      '  background: linear-gradient(to top, #5a3a0a, #c49a40);\n' +
      '  opacity: 0.95;\n' +
      '  border: 1px solid rgba(255,255,255,0.08);\n' +
      '  transform-style: preserve-3d;\n' +
      '  transform: translateZ(1px) translate(0px,103px);\n' +
      '}\n' +
      '\n' +
      '/* === GLOW SOURCES (4) === */\n' +
      '.crate-glow-0 { /* Floor glow */\n' +
      '  position: absolute;\n' +
      '  width: 582px; height: 484px;\n' +
      '  left: calc(50% - 291px + 0px);\n' +
      '  top: calc(50% - 242px + 164px);\n' +
      '  transform: translateZ(119px) rotateX(90deg) rotateY(0deg);\n' +
      '  background: radial-gradient(ellipse, rgba(220,200,160,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '  opacity: 0; transition: opacity 0.4s ease 0.15s;\n' +
      '}\n' +
      '.crate-glow-1 { /* Cross glow 1 */\n' +
      '  position: absolute;\n' +
      '  width: 458px; height: 381px;\n' +
      '  left: calc(50% - 229px + 0px);\n' +
      '  top: calc(50% - 190.5px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(0deg);\n' +
      '  background: radial-gradient(ellipse, rgba(220,200,160,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '  opacity: 0; transition: opacity 0.4s ease 0.15s;\n' +
      '}\n' +
      '.crate-glow-2 { /* Cross glow 2 */\n' +
      '  position: absolute;\n' +
      '  width: 437px; height: 363px;\n' +
      '  left: calc(50% - 218.5px + 0px);\n' +
      '  top: calc(50% - 181.5px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(60deg);\n' +
      '  background: radial-gradient(ellipse, rgba(220,200,160,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '  opacity: 0; transition: opacity 0.4s ease 0.15s;\n' +
      '}\n' +
      '.crate-glow-3 { /* Cross glow 3 */\n' +
      '  position: absolute;\n' +
      '  width: 420px; height: 349px;\n' +
      '  left: calc(50% - 210px + 0px);\n' +
      '  top: calc(50% - 174.5px + 0px);\n' +
      '  transform: translateZ(0px) rotateX(0deg) rotateY(120deg);\n' +
      '  background: radial-gradient(ellipse, rgba(220,200,160,0.6) 0%, transparent 70%);\n' +
      '  filter: blur(18px);\n' +
      '  pointer-events: none;\n' +
      '  opacity: 0; transition: opacity 0.4s ease 0.15s;\n' +
      '}\n' +
      '\n' +
      '/* Phase 3: glow visible */\n' +
      '.box3d-wrap.crate-variant.opened .crate-glow-0,\n' +
      '.box3d-wrap.crate-variant.opened .crate-glow-1,\n' +
      '.box3d-wrap.crate-variant.opened .crate-glow-2,\n' +
      '.box3d-wrap.crate-variant.opened .crate-glow-3 {\n' +
      '  opacity: 1;\n' +
      '}\n';

    var el = document.createElement('style');
    el.textContent = css;
    document.head.appendChild(el);
  }

  // ── DOM Builder ──────────────────────────────────────────────────

  function _buildWrap() {
    var SE = '<div class="sub-edge-back"></div><div class="sub-edge-left"></div><div class="sub-edge-right"></div><div class="sub-edge-top"></div><div class="sub-edge-bottom"></div>';

    var html =
      '<div class="box3d-wrap crate-variant">' +
        '<div class="box3d-scene">' +
          '<div class="box3d-spin">' +
            '<div class="box3d-body">' +
              '<div class="bf-back"></div>' +
              '<div class="bf-left">' + SE + '</div>' +
              '<div class="bf-right">' + SE + '</div>' +
              '<div class="bf-top">' + SE +
                '<div class="sub-child-0">' + SE + '</div>' +
                '<div class="sub-child-1">' + SE + '</div>' +
              '</div>' +
              '<div class="bf-bottom">' + SE + '</div>' +
              '<div class="box3d-lid-wrap">' +
                '<div class="box3d-lid">' + SE +
                  '<div class="sub-child-0"></div>' +
                  '<div class="sub-child-1"></div>' +
                  '<div class="sub-child-2"></div>' +
                '</div>' +
              '</div>' +
              '<div class="crate-glow-0"></div>' +
              '<div class="crate-glow-1"></div>' +
              '<div class="crate-glow-2"></div>' +
              '<div class="crate-glow-3"></div>' +
            '</div>' +
          '</div>' +
        '</div>' +
      '</div>';

    var wrap = document.createElement('div');
    wrap.innerHTML = html;
    return wrap.firstChild;
  }

  // ── Init ───────────────────────────────────────────────────────

  function init() {
    _injectCSS();

    _container = document.getElementById('crate-peek-container');
    if (!_container) {
      _container = document.createElement('div');
      _container.id = 'crate-peek-container';
      _container.style.cssText =
        'position:absolute; top:40%; left:50%;' +
        'transform:translate(-50%,-50%);' +
        'z-index:18; pointer-events:none; opacity:0;' +
        'transition:opacity 0.3s ease;';
      var viewport = document.getElementById('viewport');
      if (viewport) viewport.appendChild(_container);
    }

    // ── Label layer: flat div above 3D box ─────────────────────
    _labelLayer = document.getElementById('crate-peek-labels');
    if (!_labelLayer) {
      _labelLayer = document.createElement('div');
      _labelLayer.id = 'crate-peek-labels';
      _labelLayer.style.cssText =
        'position:absolute; top:0; left:0; width:100%; height:100%;' +
        'z-index:2; pointer-events:none;';
      _container.appendChild(_labelLayer);
    }

    // Inner label — "? LOOT ?", "STORAGE", "SUPPLY"
    _innerLabel = document.getElementById('crate-peek-innerlabel');
    if (!_innerLabel) {
      _innerLabel = document.createElement('div');
      _innerLabel.id = 'crate-peek-innerlabel';
      _innerLabel.style.cssText =
        'position:absolute; top:50%; left:50%;' +
        'transform:translate(-50%,-50%);' +
        'font:bold 26px monospace; color:#c8a040;' +
        'text-shadow:0 0 10px rgba(200,150,60,0.5),' +
        '            0 2px 8px rgba(0,0,0,0.9);' +
        'white-space:nowrap; pointer-events:none;' +
        'opacity:0; transition:opacity 0.3s ease 0.15s;';
      _labelLayer.appendChild(_innerLabel);
    }

    // Sub-label — type + hint
    _subLabel = document.getElementById('crate-peek-sublabel');
    if (!_subLabel) {
      _subLabel = document.createElement('div');
      _subLabel.id = 'crate-peek-sublabel';
      _subLabel.style.cssText =
        'position:absolute; top:100%; left:50%; transform:translateX(-50%);' +
        'margin-top:60px; text-align:center;' +
        'font:20px monospace; color:rgba(200,170,100,0);' +
        'text-shadow:0 1px 4px rgba(0,0,0,0.8);' +
        'transition:color 0.4s ease 0.3s; white-space:nowrap;' +
        'pointer-events:none; line-height:1.3;';
      _labelLayer.appendChild(_subLabel);
    }

    // Action button — visible click target
    _actionBtn = document.getElementById('crate-peek-action');
    if (!_actionBtn) {
      _actionBtn = document.createElement('div');
      _actionBtn.id = 'crate-peek-action';
      _actionBtn.style.cssText =
        'position:absolute; top:100%; left:50%;' +
        'transform:translateX(-50%);' +
        'margin-top:130px; min-height:48px;' +
        'font:bold 18px monospace; color:#f0d070;' +
        'text-shadow:0 0 6px rgba(240,208,112,0.3);' +
        'background:rgba(10,8,18,0.88);' +
        'border:1.5px solid rgba(200,180,120,0.55);' +
        'border-radius:10px; padding:12px 28px;' +
        'cursor:pointer; pointer-events:auto;' +
        'opacity:0; transition:opacity 0.3s ease 0.4s;' +
        'white-space:nowrap;' +
        'box-shadow:0 0 12px rgba(240,208,112,0.12);';
      _actionBtn.textContent = 'Smash';
      _actionBtn.addEventListener('click', _onActionClick);
      // Hover feedback: toggle phase 1↔2
      _actionBtn.addEventListener('mouseenter', function () {
        if (_active && _phase >= 1) {
          if (_phase === 1) {
            _wrap.classList.add('hovered');
            _phase = 2;
          }
        }
        _actionBtn.style.borderColor = '#f0d070';
        _actionBtn.style.color = '#fff';
        _actionBtn.style.boxShadow = '0 0 18px rgba(240,208,112,0.25)';
      });
      _actionBtn.addEventListener('mouseleave', function () {
        _actionBtn.style.borderColor = 'rgba(200,180,120,0.55)';
        _actionBtn.style.color = '#f0d070';
        _actionBtn.style.boxShadow = '0 0 12px rgba(240,208,112,0.12)';
      });
      _labelLayer.appendChild(_actionBtn);
    }

    // Close button
    _closeBtn = document.getElementById('crate-peek-close');
    if (!_closeBtn) {
      _closeBtn = document.createElement('div');
      _closeBtn.id = 'crate-peek-close';
      _closeBtn.style.cssText =
        'position:absolute; top:100%; left:50%;' +
        'transform:translateX(-50%);' +
        'margin-top:200px; min-height:44px;' +
        'font:16px monospace; color:rgba(200,170,100,0.55);' +
        'background:rgba(10,8,18,0.6);' +
        'border:1px solid rgba(200,180,120,0.25);' +
        'border-radius:6px; padding:10px 20px;' +
        'cursor:pointer; pointer-events:auto;' +
        'opacity:0; transition:opacity 0.3s ease 0.5s;' +
        'white-space:nowrap;';
      _closeBtn.textContent = '\u2715 Close';
      _closeBtn.addEventListener('click', function (e) {
        e.stopPropagation();
        _hide();
      });
      _closeBtn.addEventListener('mouseenter', function () {
        _closeBtn.style.borderColor = 'rgba(200,180,120,0.55)';
        _closeBtn.style.color       = 'rgba(240,220,160,0.8)';
      });
      _closeBtn.addEventListener('mouseleave', function () {
        _closeBtn.style.borderColor = 'rgba(200,180,120,0.25)';
        _closeBtn.style.color       = 'rgba(200,170,100,0.55)';
      });
      _labelLayer.appendChild(_closeBtn);
    }
  }

  // ── Action button click ────────────────────────────────────────

  function _onActionClick(e) {
    e.stopPropagation();
    if (!_active) return;

    // Flash feedback
    if (_actionBtn) {
      _actionBtn.style.background = 'rgba(240,220,140,0.3)';
      setTimeout(function () {
        if (_actionBtn) _actionBtn.style.background = 'rgba(10,8,18,0.88)';
      }, 150);
    }

    // Trigger phase 3
    _triggerPhase3();
  }

  // ── Phase 3 trigger ────────────────────────────────────────────

  function _triggerPhase3() {
    if (_phase === 3 || !_active) return;
    _phase = 3;
    if (_wrap) {
      _wrap.classList.remove('hovered');
      _wrap.classList.add('opened');
    }
    if (typeof AudioSystem !== 'undefined') AudioSystem.play('ui-confirm', { volume: 0.4 });
    // Fire interaction
    if (typeof Game !== 'undefined' && typeof Game.interact === 'function') {
      Game.interact();
    }
  }

  // ── Per-frame check ────────────────────────────────────────────

  function update(dt) {
    if (!_container || typeof FloorManager === 'undefined') return;

    var floorData = FloorManager.getFloorData();
    if (!floorData) { _hide(); return; }

    var p   = Player.getPos();
    var dir = Player.getDir();
    var fx  = p.x + MC.DX[dir];
    var fy  = p.y + MC.DY[dir];

    if (fx < 0 || fx >= floorData.gridW || fy < 0 || fy >= floorData.gridH) {
      _hide(); return;
    }

    var tile = floorData.grid[fy][fx];
    if (tile !== TILES.BREAKABLE) { _hide(); return; }

    // Same tile we were already peeking at — hold steady
    if (_active && _facingTile === tile && _facingX === fx && _facingY === fy) {
      // Input edge detection for forward/back
      var IM = (typeof InputManager !== 'undefined') ? InputManager : null;
      if (IM) {
        var fwdDown = IM.isDown('step_forward');
        var backDown = IM.isDown('step_back');
        var fwdEdge = fwdDown && !_prevForward;
        var backEdge = backDown && !_prevBack;
        _prevForward = fwdDown;
        _prevBack = backDown;

        if (backEdge) { _hide(); return; }
        if (fwdEdge && _phase >= 1) { _triggerPhase3(); return; }
      }
      return;
    }

    // Different tile while active — dismiss first, reset debounce
    if (_active && (_facingX !== fx || _facingY !== fy)) {
      _hide();
    }

    // New tile — accumulate debounce
    _facingTile = tile;
    _facingX    = fx;
    _facingY    = fy;
    _timer     += dt;

    if (_timer >= SHOW_DELAY) {
      _show(tile, fx, fy, floorData);
    }
  }

  // ── Show / hide ────────────────────────────────────────────────

  function _show(tile, fx, fy, floorData) {
    if (_active) _destroyWrap();
    if (typeof AudioSystem !== 'undefined') AudioSystem.play('ui-popup', { volume: 0.4 });

    _phase = 1;
    _active = true;
    _timer = 0;

    // Determine crate type
    var _cpFloorId = typeof FloorManager !== 'undefined' ? FloorManager.getCurrentFloorId() : '';
    var _cpContainer = (typeof CrateSystem !== 'undefined')
      ? CrateSystem.getContainer(fx, fy, _cpFloorId) : null;
    var isSupply = !!_cpContainer && !_cpContainer.storage;
    var isStorage = !!_cpContainer && !!_cpContainer.storage;

    // Build and append wrap
    _wrap = _buildWrap();
    _wrap.style.pointerEvents = 'none';
    _wrap.style.position = 'relative';
    _wrap.style.zIndex = '1';
    _container.insertBefore(_wrap, _labelLayer);

    // Inner label
    var _cpInner = isStorage ? '\uD83D\uDCE6 STORAGE' : (isSupply ? '\u2691 SUPPLY' : '? LOOT ?');
    if (_innerLabel) {
      _innerLabel.textContent = _cpInner;
      _innerLabel.style.opacity = '0';
    }

    // Sub-label
    var _cpSub  = isStorage ? 'storage crate' : (isSupply ? 'supply crate' : 'breakable crate');
    var _cpHint = isStorage ? '\u2192 open for supplies'
                : (isSupply ? '\u2192 restock slots' : '\u2192 smash to loot');
    if (_subLabel) {
      _subLabel.textContent = '';
      _subLabel.appendChild(document.createTextNode(_cpSub));
      _subLabel.appendChild(document.createElement('br'));
      _subLabel.appendChild(document.createTextNode(_cpHint));
      _subLabel.style.color = 'rgba(200,170,100,0)';
    }

    // Action button
    var _cpBtn = isStorage ? 'Open' : (isSupply ? 'Restock' : 'Smash');  // 'Fill Crate' → 'Restock' per GOLF_DAY1_AUDIT.md.
    if (_actionBtn) {
      _actionBtn.textContent = _cpBtn;
      _actionBtn.style.opacity = '0';
      _actionBtn.style.pointerEvents = 'none';
    }
    if (_closeBtn) { _closeBtn.style.opacity = '0'; _closeBtn.style.pointerEvents = 'none'; }

    _container.style.opacity = '1';

    // Auto-crack: phase 1 → phase 2
    setTimeout(function () {
      if (_active && _phase === 1 && _wrap) {
        // Show labels
        if (_innerLabel) _innerLabel.style.opacity = '1';
        if (_subLabel) _subLabel.style.color = 'rgba(200,170,100,0.9)';
        if (_actionBtn) {
          _actionBtn.style.opacity = '1';
          _actionBtn.style.pointerEvents = 'auto';
        }
        if (_closeBtn) { _closeBtn.style.opacity = '1'; _closeBtn.style.pointerEvents = 'auto'; }
        // Auto-transition to phase 2
        setTimeout(function () {
          if (_active && _phase === 1 && _wrap) {
            _wrap.classList.add('hovered');
            _phase = 2;
          }
        }, 200);
      }
    }, 150);
  }

  function _hide() {
    if (!_active) { _timer = 0; return; }
    if (typeof AudioSystem !== 'undefined') AudioSystem.play('ui-click', { volume: 0.3 });

    if (_wrap) _wrap.classList.remove('opened', 'hovered');

    _container.style.opacity = '0';
    if (_innerLabel) _innerLabel.style.opacity = '0';
    if (_subLabel) _subLabel.style.color = 'rgba(200,170,100,0)';
    if (_actionBtn) {
      _actionBtn.style.opacity = '0';
      _actionBtn.style.pointerEvents = 'none';
    }
    if (_closeBtn) { _closeBtn.style.opacity = '0'; _closeBtn.style.pointerEvents = 'none'; }

    setTimeout(function () { _destroyWrap(); }, 400);

    _resetState();
  }

  function _destroyWrap() {
    if (_wrap && _wrap.parentNode) _wrap.parentNode.removeChild(_wrap);
    _wrap = null;
  }

  function _resetState() {
    _active     = false;
    _phase      = 0;
    _facingTile = 0;
    _facingX    = -1;
    _facingY    = -1;
    _timer      = 0;
    _prevForward = false;
    _prevBack    = false;
  }

  function handleKey(key) {
    if (!_active) return false;
    if (key === 'Escape') { _hide(); return true; }
    return false;
  }

  function isActive() { return _active; }
  function forceHide() { _hide(); }

  // ── Public API ─────────────────────────────────────────────────

  return Object.freeze({
    init:      init,
    update:    update,
    handleKey: handleKey,
    isActive:  isActive,
    forceHide: forceHide
  });
})();
