# stamp-build.ps1 — regenerate engine/game-build-stamp.js from the current
# git state. PowerShell sibling of stamp-build.sh. See
# docs/BUILD_VERSION_POLICY.md (DOC-129) for the full policy.
$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $PSCommandPath
$root = Split-Path -Parent $here
Set-Location $root

if (-not (Test-Path '.git')) {
    Write-Error "stamp-build: not inside a git repository (cwd=$root)"
    exit 1
}

$commitHash = (git rev-parse --short=7 HEAD).Trim()
$commitDate = (git show -s --format=%cs HEAD).Trim()
$stampedAt  = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

git diff-index --quiet HEAD -- 2>$null
$indexClean = ($LASTEXITCODE -eq 0)
$untracked  = (git ls-files --others --exclude-standard)

if ($indexClean -and [string]::IsNullOrWhiteSpace($untracked)) {
    $dirty = 'false'
    $dirtyMarker = ''
} else {
    $dirty = 'true'
    $dirtyMarker = '+dirty'
}

$semverMatch = Select-String -Path 'engine/save-state.js' `
    -Pattern "BUILD_VERSION = '([^']+)'" | Select-Object -First 1
if ($semverMatch) {
    $semver = $semverMatch.Matches[0].Groups[1].Value
} else {
    Write-Warning "stamp-build: could not read BUILD_VERSION from engine/save-state.js"
    $semver = '0.0.0-nostamp'
}

$display = "build $semver · $commitHash$dirtyMarker · $commitDate"

$js = @"
/**
 * game-build-stamp.js — playtester-facing build identifier.
 *
 * GENERATED by scripts/stamp-build.ps1 at $stampedAt.
 * DO NOT HAND-EDIT. Re-run the stamp script instead.
 *
 * See engine/game-build-stamp.js (source template) and
 * docs/BUILD_VERSION_POLICY.md (DOC-129) for the workflow.
 */
(function () {
  'use strict';

  var stamp = {
    commitHash: '$commitHash',
    commitDate: '$commitDate',
    dirty: $dirty,
    semver: '$semver',
    stampedAt: '$stampedAt',
    display: '$display'
  };

  if (typeof window !== 'undefined') {
    window.GameBuildStamp = stamp;
  }
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = stamp;
  }
}());
"@

Set-Content -Path 'engine/game-build-stamp.js' -Value $js -NoNewline

Write-Host "Stamped: $display" -ForegroundColor Green
