#!/usr/bin/env bash
# Regenerate engine/game-build-stamp.js from the current git state so
# playtesters can cite the exact commit they played when reporting bugs.
#
# Run before `git push` on any branch playtesters pull from.
# Wired into the `just stamp-build` recipe and the `dg-stamp-build` profile
# function.
#
# See docs/BUILD_VERSION_POLICY.md (DOC-129) for the full policy.

set -euo pipefail

_here="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
_root="$(cd "$_here/.." && pwd)"
cd "$_root"

if ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "stamp-build: not inside a git repository (cwd=$_root)" >&2
    exit 1
fi

commit_hash="$(git rev-parse --short=7 HEAD)"
commit_date="$(git show -s --format=%cs HEAD)"   # author commit date, YYYY-MM-DD
stamped_at="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

if git diff-index --quiet HEAD -- && \
   [ -z "$(git ls-files --others --exclude-standard)" ]; then
    dirty="false"
    dirty_marker=""
else
    dirty="true"
    dirty_marker="+dirty"
fi

# Pull the shipped semver from SaveState so the stamp always agrees with
# the schema gate. If the grep fails for any reason, fall back to 0.0.0
# and fail loudly — no stamp is preferable to a misleading one.
semver="$(grep -oE "BUILD_VERSION = '[^']+'" engine/save-state.js \
    | head -1 | sed -E "s/.*'([^']+)'.*/\1/")"
if [ -z "$semver" ]; then
    echo "stamp-build: could not read BUILD_VERSION from engine/save-state.js" >&2
    semver="0.0.0-nostamp"
fi

display="build ${semver} · ${commit_hash}${dirty_marker} · ${commit_date}"

cat > engine/game-build-stamp.js <<EOF
/**
 * game-build-stamp.js — playtester-facing build identifier.
 *
 * GENERATED by scripts/stamp-build.sh at ${stamped_at}.
 * DO NOT HAND-EDIT. Re-run the stamp script instead.
 *
 * See engine/game-build-stamp.js (source template) and
 * docs/BUILD_VERSION_POLICY.md (DOC-129) for the workflow.
 */
(function () {
  'use strict';

  var stamp = {
    commitHash: '${commit_hash}',
    commitDate: '${commit_date}',
    dirty: ${dirty},
    semver: '${semver}',
    stampedAt: '${stamped_at}',
    display: '${display}'
  };

  if (typeof window !== 'undefined') {
    window.GameBuildStamp = stamp;
  }
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = stamp;
  }
}());
EOF

printf '\033[32mStamped: %s\033[0m\n' "$display"
