// ═══════════════════════════════════════════════════════════════
//  tools/cli/bf-emit.js — `bf emit`
//
//  Phase 3a of BOXFORGE_AGENT_ROADMAP.
//
//  Produces a deterministic peek module at engine/<variant>-peek.js
//  from a sidecar at tools/templates/peeks/<variant>.boxforge.json.
//
//  The emitted module uses the PeekShell.register pattern (engine/
//  peek-shell.js) with the descriptor fields resolved by the
//  BoxForge sandbox's resolveDescriptor + buildMeta helpers. The CSS
//  and DOM for the 3D box are generated by tools/cli/bf-css-emit.js,
//  which is a faithful pure-Node port of generateExportCSS from
//  boxforge.html (§4914).
//
//  The full v4 sidecar JSON is embedded at the bottom of the emitted
//  module as a `/* BF-DATA-START\n{...}\nBF-DATA-END */` block —
//  that's what makes the bf ingest round-trip deterministic.
//
//  Usage:
//    bf emit --variant <v> --as peek-module --out engine/<v>-peek.js
//    bf emit --variant <v>                             # derives --out
//    bf emit --variant <v> --print                    # stdout only
//    bf emit --variant <v> --dry-run                  # suppressed write
//    bf emit --variant <v> --overwrite                # replace existing module
//
//  Exit codes: 0 ok, 1 usage, 2 runtime.
// ═══════════════════════════════════════════════════════════════
'use strict';

var S = require('./bf-shared');
var SANDBOX = require('./bf-peek-sandbox');
var CSS = require('./bf-css-emit');

var SUPPORTED_AS = { 'peek-module': 1 };

function fileNameForVariant(variant) {
  return variant + '-peek.js';
}

// Render a compact JS literal for a value — used for inlining the
// descriptor into the emitted module. Keeps key ordering stable so
// the scaffold is byte-stable across runs.
function jsLit(val, indent) {
  indent = indent || '';
  var next = indent + '  ';
  if (val === null || val === undefined) return 'null';
  if (typeof val === 'boolean' || typeof val === 'number') return String(val);
  if (typeof val === 'string') return JSON.stringify(val);
  if (Array.isArray(val)) {
    if (!val.length) return '[]';
    return '[\n' + val.map(function(v) { return next + jsLit(v, next); }).join(',\n') + '\n' + indent + ']';
  }
  if (typeof val === 'object') {
    var keys = Object.keys(val);
    if (!keys.length) return '{}';
    return '{\n' + keys.map(function(k) {
      return next + JSON.stringify(k) + ': ' + jsLit(val[k], next);
    }).join(',\n') + '\n' + indent + '}';
  }
  return 'null';
}

// Render the scaffold — a minimal IIFE that calls PeekShell.register.
// The emitted module is deliberately thin: the 3D box chrome is in
// the CSS/HTML pair, and everything behavioral flows through the
// descriptor callbacks (onMount / onInteract / onKey / onUnmount).
function renderPeekModule(opts) {
  var variant = opts.variant;
  var descriptor = opts.descriptor;
  var meta = opts.meta || null;
  var css = opts.css;
  var html = opts.html;
  var sidecarJson = opts.sidecarJson;
  var headerName = opts.templateName || variant;
  var generatedAt = opts.generatedAt || new Date().toISOString();

  var banner = [
    '// \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550',
    '//  engine/' + variant + '-peek.js \u2014 BoxForge-generated peek module',
    '//  Template: ' + headerName,
    '//  Generated: ' + generatedAt,
    '//  Source sidecar: tools/templates/peeks/' + variant + '.boxforge.json',
    '//',
    '//  This file was emitted by `bf emit --variant ' + variant + '`.',
    '//  DO NOT hand-edit. Round-trip via `bf ingest --variant ' + variant + '`',
    '//  to re-hydrate the sidecar; re-run `bf emit` to regenerate.',
    '//',
    '//  Behavioural wiring (onMount / onInteract / onKey / onUnmount)',
    '//  should extend this scaffold in a sibling module or via a',
    '//  jsHandoffModule hook \u2014 not by editing this generated file.',
    '// \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550'
  ].join('\n');

  // CSS injector: append a <style> tag once per document.
  var cssStyleId = 'bf-css-' + variant;
  var cssLit = JSON.stringify(css);
  var htmlLit = JSON.stringify(html);
  var descriptorLit = jsLit(descriptor, '  ');

  var body = [
    banner,
    "'use strict';",
    '',
    '(function() {',
    '  if (typeof window === \'undefined\' || !window.PeekShell) return;',
    '  var PeekShell = window.PeekShell;',
    '  var STYLE_ID = ' + JSON.stringify(cssStyleId) + ';',
    '  var CSS = ' + cssLit + ';',
    '  var HTML = ' + htmlLit + ';',
    '',
    '  function ensureStyle() {',
    '    if (document.getElementById(STYLE_ID)) return;',
    '    var s = document.createElement(\'style\');',
    '    s.id = STYLE_ID;',
    '    s.textContent = CSS;',
    '    document.head.appendChild(s);',
    '  }',
    '',
    '  function makeContentEl() {',
    '    ensureStyle();',
    '    var host = document.createElement(\'div\');',
    '    host.className = \'bf-peek-host bf-peek-' + variant + '\';',
    '    host.innerHTML = HTML;',
    '    return host;',
    '  }',
    '',
    '  var DESC = ' + descriptorLit + ';',
    '',
    '  // Bind contentEl factory (PeekShell expects a DOM node)',
    '  DESC.contentEl = makeContentEl;',
    '',
    '  PeekShell.register(DESC);',
    '})();',
    '',
    '/* BF-DATA-START',
    sidecarJson,
    'BF-DATA-END */',
    ''
  ].join('\n');

  return body;
}

function run(args) {
  var variant = args.variant ? String(args.variant) : null;
  if (!variant) S.fail(1, 'emit needs --variant <name>');

  var asKind = args.as ? String(args.as) : 'peek-module';
  if (!SUPPORTED_AS[asKind]) {
    S.fail(1, 'emit: unsupported --as "' + asKind + '" (supported: ' + Object.keys(SUPPORTED_AS).join(', ') + ')');
  }

  // 1. Load + validate sidecar via bf-shared canonical helpers.
  var data = S.loadPeekFile(variant);
  var sb = S.getBoxForgeSandbox();
  var vres = sb.validateProject(data);
  if (!vres || !vres.ok) {
    var errs = (vres && vres.errors) || ['unknown validation error'];
    S.fail(2, 'emit: sidecar validation failed for "' + variant + '":\n  - ' + errs.join('\n  - '));
  }

  // 2. Reconcile descriptor + meta with the canonical resolvers so
  //    overrides declared in boxforge.html still apply even if the
  //    sidecar was hand-edited.
  var templateName = data.templateName || variant;
  var resolved = sb.resolveDescriptor(templateName) || {};
  var builtMeta = sb.buildMeta(templateName) || null;

  // Sidecar-declared fields win; resolver fills in any gaps.
  var descriptor = Object.assign({}, resolved, data.descriptor || {});
  // Always pin variant + tileMatch from the sidecar so `bf ingest`
  // sees the same shape it wrote.
  descriptor.variant = data.descriptor && data.descriptor.variant || variant;
  if (data.descriptor && data.descriptor.tileMatch) descriptor.tileMatch = data.descriptor.tileMatch;

  var meta = data.meta || builtMeta;

  // 3. Generate CSS + HTML from the sidecar. emitCSS is a pure port
  //    of the browser tool's generateExportCSS (boxforge.html#4914).
  var cssRes = CSS.emitCSS(data, templateName);
  var htmlStr = CSS.emitHTML(data, templateName);

  // 4. Re-serialize the sidecar exactly the way bf-shared.savePeekFile
  //    would write it to disk (2-space JSON + trailing newline). That
  //    gives us byte-stable round-trip through the BF-DATA block.
  var sidecarJson = JSON.stringify(data, null, 2);

  // 5. Render the scaffold.
  var source = renderPeekModule({
    variant: variant,
    templateName: templateName,
    descriptor: descriptor,
    meta: meta,
    css: cssRes.css,
    html: htmlStr,
    sidecarJson: sidecarJson
  });

  // 6. Resolve --out. Default is engine/<variant>-peek.js.
  var outRel = args.out ? String(args.out) : S.path.join('engine', fileNameForVariant(variant));
  var outAbs = S.path.isAbsolute(outRel) ? outRel : S.path.join(SANDBOX.ROOT, outRel);

  // --print: stdout only, no writes.
  if (args.print) {
    process.stdout.write(source);
    return;
  }

  var existsAlready = S.fs.existsSync(outAbs);
  if (existsAlready && !args.overwrite) {
    // If the new source is byte-identical, treat as a no-op (same
    // safety rail bf-ingest uses when re-saving an unchanged sidecar).
    var existing = S.fs.readFileSync(outAbs, 'utf8');
    if (existing !== source) {
      S.fail(1, 'emit: target exists and differs at ' + S.path.relative(SANDBOX.ROOT, outAbs) +
              ' \u2014 pass --overwrite to replace (or --print / --dry-run to preview)');
    }
  }

  var cssLen = cssRes.css.length;
  var htmlLen = htmlStr.length;
  var srcLen = source.length;

  if (S.isDryRun()) {
    // Envelope semantics: increment save-call counter without writing,
    // mirroring bf-shared.savePeekFile.
    S.setDryRun(true); // stay in dry-run
    // We don't have a dedicated save helper for engine files, so
    // synthesize the same counter bump via the sidecar helper:
    //   (savePeekFile increments _saveCallCount and returns when dry.)
    //   We re-save the parsed sidecar to capture one suppressed write.
    S.savePeekFile(variant, data);
  } else {
    S.fs.writeFileSync(outAbs, source);
  }

  process.stdout.write(JSON.stringify({
    ok: true,
    action: 'emit',
    variant: variant,
    as: asKind,
    dryRun: !!S.isDryRun(),
    wrote: S.isDryRun() ? null : S.path.relative(SANDBOX.ROOT, outAbs),
    target: S.path.relative(SANDBOX.ROOT, outAbs),
    cssBytes: cssLen,
    htmlBytes: htmlLen,
    sourceBytes: srcLen,
    descriptor: {
      variant: descriptor.variant,
      tileMatch: descriptor.tileMatch || null,
      showDelay: descriptor.showDelay || null,
      kindId: descriptor.kindId || null
    },
    meta: meta ? { status: meta.status || null } : null
  }, null, 2) + '\n');
}

module.exports = {
  'emit': run,
  '_renderPeekModule': renderPeekModule,
  '_fileNameForVariant': fileNameForVariant
};
